### ISSUE TITLE
Run performance measurements on build farm hosts, and log results to database

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1082]
*Issue migrated from trac ticket # 1080*

**component:** General | **priority:** major

#### 2012-10-02 09:59:28: @jkeiren created the issue

___
Currently the performance measurements are run on pclin164. This host is old, and needs to be replaced.

The performance measurement scripts should be modified such that they can be run on arbitrary hosts, and that their results can be logged to a MySQL database.

**Comment by mlaveaux** [comment]
The existing performance benchmark setup has been recreated in our cmake scripts. It is now possible to replicate this setup on every machine. Additionally, the performance benchmark is executed every night on our TeamCity build servers and the results are presented as several plots showing the differences over time.
