### ISSUE TITLE
Clean up and organise test cases

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1088]
*Issue migrated from trac ticket # 1086*

**component:** General | **priority:** minor

#### 2012-10-04 08:31:14: @jkeiren created the issue

___
Currently test cases are spread in the toolset on a fairly ad-hoc basis. Test cases should be cleaned up, and treated in a uniform way.

At the moment we use several forms of testing:

 - Regression tests for bugs that have been found previously.
 - End to end tests of algorithms, implemented as unit-test.
 - End to end tests of tools, implemented by calling tools on examples.
 - End to end tests based on random testing.

**Comment by mlaveaux** [comment]
All test cases can be executed using ctest, which is part of the cmake build system that we use, which allows them be executed in a uniform way.  Underlying these test cases there are several python scripts which could be improved, but then a new issue should be opened that highlights concrete improvements that should/can be made to these scripts.
