### ISSUE TITLE
PBES blowup after conversion to PFNF

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1093]
*Issue migrated from trac ticket # 1091*

**component:** lps2pbes | **priority:** minor

#### 2012-10-08 20:07:08: @twillems created the issue

___
Attached is a (minimal) example that shows that the (PBES) rewriters are not sufficiently powerful to prevent blowup after conversion to PFNF (from 4 equations, we needlessly go to 7; the root cause seems to be the inability to detect `X = X && (X || Y)`).

This seems to lead to excessive memory usage on some machines.

To reproduce:
```
txt2pbes pfnf.txt pfnf.pbes
pbes2bool pfnf.pbes -v
pbesinst -slazy pfnf.pbes |bespp
pbesrewr -ppfnf pfnf.pbes pfnf.pfnf.pbes
pbes2bool -v pfnf.pfnf.pbes
pbesinst -slazy pfnf.pfnf.pbes |bespp
```

**Comment by wiegerw** [comment]
I propose to close this issue. The conversion has been implemented according to a specification, and I don't have any plans to deviate from that. It is a known fact that this conversion to PFNF may lead to exponential blowup.

**Comment by jgroote** [comment]
I have the tendency to agree with closing this request. The PFNF normal form is a disjunctive
normal form and this indeed blows up. One can try to implement all kinds of tricks to keep such 
a blowup small, but this can only alleviate the problem somewhat. Therefore I close this ticket upon suggestion by Wieger.
