### ISSUE TITLE
Make the generation of rewrite rules from scripts type dependent.

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1227]
*Issue migrated from trac ticket # 1226*

**component:** Data Library | **priority:** minor

#### 2013-10-21 13:45:33: @jgroote created the issue

___
In the specification files to generate the rewrite rules
for the data types it is currently not possible to use
overloaded function symbols. This regards files like nat.spec,
pos.spec, fset.spec etc.

For instance it is sometimes useful to use - (minus) on positive
numbers in an fset. But as - is also used for set subtraction,
there is a conflict. The system always prefers the - on fsets,
even if the arguments are of type Pos.

Making the python script type dependent would solve this problem.

The current solution is now to introduce auxiliary functions
with different names in the data types but this is ugly.

**Comment by tneele** [comment]
We no longer see this as a problem.
