### ISSUE TITLE
Typechecking of assignments is insufficiently strict.

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1304]
*Issue migrated from trac ticket # 1303*

**component:** Core: Type-checker Library | **priority:** minor

#### 2014-07-30 20:50:40: @jgroote created the issue

___
The following example is currently accepted by the
typechecker of the toolset. However, the typechecking rules
describe that the assignment syntax can only be used in
single equations where the left and right hand side are
the same. This should be mended.

```
proc P(b, c: Bool) = delta;
proc Q(b, d: Bool) = P(c = d);

init Q(true, true);
```

Example has been provided by Wieger Wesselink.

**Comment by wiegerw** [comment]
This ticket was based on a quote in the mcrl2 book on page 63, that explicitly forbids the construction in this example. However, in practice it is being used a lot, and there seems to be no good reason to forbid it. So the changes in 37ec1b0 will be reverted again.
