### ISSUE TITLE
improve the efficiency of duplicate process equation removal

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1314]
*Issue migrated from trac ticket # 1313*

**component:** Core: Alpha Library | **priority:** minor

#### 2014-12-09 21:20:42: @wiegerw created the issue

___
The function process::remove_duplicate_equations applies a naive bisimulation algorithm for detecting duplicate equations. This turns out to be a bottle neck for the attached specification.

A more efficient procedure for removing duplicate equations is needed. A generic, efficient bisimulation implementation would of course be very useful.

**Comment by wiegerw** [comment]
The issue has been resolved in alphabet reduction by only applying the procedure when the number of process variables is small. This is the only use case of this procedure, so I will close this ticket.
