### ISSUE TITLE
Improve performance of process library algorithms by only considering the reachable equations

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1362]
*Issue migrated from trac ticket # 1361*

**component:** Process Library | **priority:** minor

#### 2016-10-10 16:11:57: @wiegerw created the issue

___
Some algorithms in the process library (like compute_pcrl_equation_cache) perform operations on all equations. Their performance can be improved by operating on the reachable equations only.

**Comment by wiegerw** [comment]
For the most important use cases this problem has been resolved. So I will close this ticket.
