### ISSUE TITLE
Simplify the API of lps2lts_algorithm

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1392]
*Issue migrated from trac ticket # 1391*

**component:** LTS Library | **priority:** minor

#### 2017-03-14 15:29:09: @tneele created the issue

___
The API that allows exploration of a linear process is complicated and inflexible. Currently, something along these lines is required to generate an LTS:

```
lps2lts_algorithm expl;
lts_generation_options opts;
opts.specification = input_lps;
opts.lts = "/tmp/temp.lts";
opts.outformat = lts_type::lts_lts;
expl.initialise_lts_generation(&opts);
expl.generate_lts();
expl.finalise_lts_generation();
lts_lts_t output_lts;
output_lts.load("/tmp/temp.lts");
```

APIs for linearising specifications and minimising transition systems are much more simple: they just require one function call and don't require the result to be written to disk.

A note about the internals of `lps2lts_algorithm`: it should be agnostic of the output format. I guess the fact that the API is so inflexible is related to the fact that there are many checks on the output format.

**Comment by tneele** [comment]
With @wiegerw's work on the new implementation for lps2lts, I consider this issue obsolete and/or resolved.
