### ISSUE TITLE
ltsgraph and ltsview do not accept input from stdin

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1396]
*Issue migrated from trac ticket # 1395*

**component:** ltsgraph | **priority:** minor

#### 2017-03-28 16:31:04: @tneele created the issue

___
At the moment, ltsgraph and ltsview do not accept an input lts from stdin. Since these tools can also be executed without a command line argument (the user can open an lts later with the GUI), I propose to use a minus sign '-' to indicate stdin should be read.

Using a minus sign is a standard way to refer to stdin. For example the man page of 'cat' says: "With no FILE, or when FILE is -, read standard input."

**Comment by tneele** [comment]
It was relatively easy to fix this for ltsgraph. For ltsview it was more involved, so I left that as it is, since reading from stdin is mostly useful for small LTSs.
