### ISSUE TITLE
ltsgraph quits unexpectedly.

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1423]
*Issue migrated from trac ticket # 1422*

**component:** ltsgraph | **priority:** minor

#### 2017-07-08 11:52:32: @jgroote created the issue

___
When terminating ltsgraph on an arbitrary transition system it indicates that
it quits unexpectedly on a mac. 

This does not hamper functioning of ltsgraph, but it looks careless.

**Comment by tneele** [comment]
This issue has not occurred in a while, so i will close it.
