### ISSUE TITLE
Timed linearisation introduces unnecessary conditions through merge_vars

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1425]
*Issue migrated from trac ticket # 1424*

**component:** LPS Library | **priority:** minor

#### 2017-07-10 10:31:42: @tneele created the issue

___
During the construction of ultimate delay conditions, the function merge_var is called (line 8557 of linearise.cpp). This function was intended for construction of conditions for clustered summands. As an optimalisation, it introduces additional conditions on the newly-introduced sum variables. These conditions are unnecessary for ultimate delay conditions.

**Comment by tneele** [comment]
In hindsight, the conditions introduced by merge_vars are useful to speed up the enumerator, also in ultimate delay conditions. No change is needed.
