### ISSUE TITLE
selecting/using multiple files in mCRL2-gui for lps2pbes transformation

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1440]
*Issue migrated from trac ticket # 1440*

**component:** mcrl2-gui | **priority:** major

#### 2017-10-25 09:45:03: @twillems created the issue

___
It would be natural (at least potentially more user-friendly) for the mcrl2-gui tool to automatically fill in the 'formula' checkbox in the lps2pbes transformation in case both an LPS and a mu-calculus object is selected; in that case the formula to be used is the second file that is selected. 

In a similar vein, the lts2pbes transformation could insert the right information in the respective fields based on the files that have been selected.

**Comment by tneele** [comment]
Sorry, @twillems, but we will not spend effort on this for now. A good alternative is to drag the .mcf file to the box where you would fill in the path to the .mcf file.
