### ISSUE TITLE
CMake build files are too complicated

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1451]
*Issue migrated from trac ticket # 1451*

**component:** Build system | **priority:** major

#### 2017-12-05 13:48:35: @wiegerw created the issue

___
The CMake files of the tool set are effectively unmaintainable. Too much functionality has been coded away in undocumented functions like add_mcrl2_library. This makes it hard or impossible to make local adaptations. Moreover, modern IDE's cannot understand our CMake files, which makes it very complicated to use them for mCRL2 development.

**Comment by mlaveaux** [comment]
We have certain functionality that relies on a central add_mcrl2_binary to register all the tools that are being compiled. In principle we could refactor our tools and libraries to make use of the provided cmake functionality, but provided that we have to support old versions (such as 3.14) for our ubuntu user base this is rather tricky. Quite some effort has been put into simplifying various aspects of our cmake configuration over time. If there is concrete suggestions we should look into it in new issues.
