### ISSUE TITLE
Weird resolution of processes with same names

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1452]
*Issue migrated from trac ticket # 1452*

**component:** General | **priority:** minor

#### 2018-01-15 21:03:01: volkerlanting@gmail.com created the issue

___
When I have two processes with the same name, process calls with assigned parameters lead to weird resolution of the process.

Let's take the following example:

```
init p(a=5);
act BoolParam, IntParam;
proc
  p(a:Bool) = BoolParam;
  p(b:Int) = IntParam; 
```

I would expect a type error, as the only process 'p' with a parameter 'a' is 'p(a:Bool)', but our assigned process call 'p(a=5)' assigns an argument of type Int.

Instead, this program parses and passes the type checks. And when I inspect the LTS it shows that the second process was selected (the one that does the 'IntParam' action). This seems like a bug to me, as that process has no parameter named 'a' and the init statement specifically assigns to the 'a' parameter.

It gets interesting with more parameters. In the next example, the 'c' parameter needs to be of the correct type and in the correct location in the parameter list for the specification to pass the type checks:

```
init tempProcess(true);
act BoolParam, IntParam;
proc
  tempProcess(x:Bool) = p(a=5);
  p(a:Bool, x:Bool) = BoolParam;
  p(b:Int, c:Bool) = IntParam; 
```

This example also creates an LTS that performs the 'IntParam' action. But if you change the type of parameter 'c' to 'Int', or move it in front of parameter 'b', the type checker raises an error.

So my guess is that finding a process based on the assigned parameters, and actually type checking the arguments and parameters are two separate steps.
The first step selects the first definition of process 'p', but the type checker selects the second.

Or is this intended behaviour?

**Comment by wiegerw** [comment]
In both cases the expression p(a = 5) is now rejected by the type checker.
