### ISSUE TITLE
Type checking with many sort aliases is slow

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1456]
*Issue migrated from trac ticket # 1456*

**component:** Core: Type-checker Library | **priority:** major

#### 2018-03-14 17:48:09: @jgroote created the issue

___
Using sort aliases causes type checking and linearisation to slow down significantly (from a couple of seconds to fifteen minutes in the case below) while generating an lps file.

e.g.

sort
    A_t = Nat;
    B_t = Nat;
    C_t = Nat;
    D_t = Nat;
    E_t = Nat;
    F_t = Nat;
    G_t = Nat;

S_t = struct s(
    A:A_t,
    B:B_t,
    C:C_t,
    D:D_t,
    E:E_t,
    F:F_t,
    G:G_t
);

act
    a;
proc
    P = a;
init
    P;

Is this expected behaviour, or I have I missed something?

Thank you in advance!

Best regards,
Aleksi Peltonen

**Comment by tneele** [comment]
Might be solved, Jan Friso will do further investigation.

**Comment by jgroote** [comment]
This problem has been resolved on May 20, 2018 in commit 7ffb3b2, or
in svn revision 15361. Apparently, this ticket was not closed.
