### ISSUE TITLE
Undetected ambiguity in structured sorts

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1460]
*Issue migrated from trac ticket # 1460*

**component:** Core: Type-checker Library | **priority:** major

#### 2018-04-09 18:28:07: @wiegerw created the issue

___
The following invalid process specification can be parsed and type checked without problems. It seems to me that the data checker should detect the ambiguity in the expression i(s).

```
sort
  S = struct S1(i: Int) | S2(i: Bool);

act
  a;

proc
  P(s: S) = i(s) -> a . P();

init
  P(S1(0));
```

**Comment by tneele** [comment]
Applying mcrl22lps and lps2lts on this specification lead to the error `Error while exploring state space: Expression i(S1(0)) does not rewrite to true or false in the condition i(S1(0))` from lps2lts.

**Comment by jgroote** [comment]
I do not think this is a bug in the type checker. The problem is inherent in the 
specification. If we change the specification to the one below, exactly the same problem
occurs. The type checker finds the correct function "i" with target sort bool and applies it. 
For the situation below no rewrite rules are provided, and this is appropriately reported. 

sort
  S = struct S1(i_int: Int) | S2(i_bool: Bool);

act
  a;

proc
  P(s: S) = i_bool(s) -> a . P();

init
  P(S1(0));

**Comment by jgroote** [comment]
We can change the example such that type checking cannot be resolved anymore. 
This is also properly reported. See the example below. 

sort
  S = struct S1(i: Int) | S2(i: Bool);

map f:Bool->Bool;
    f:Int->Bool;

act
  a;

proc
  P(s: S) = f(i(s)) -> a . P();

init
  P(S1(0));

mcrl22lps test.mcrl2 temp.lps
[error]   Fail to properly type i(s).

**Comment by tneele** [comment]
> I do not think this is a bug in the type checker. The problem is inherent in the specification.

I agree with @jgroote on this; the provided specification is not ill-typed. The specification contains a condition that is partially undefined, and it is hard to detect in the lineariser whether this will cause problems during state space generation. In the provided example, the condition is undefined for the value `S1(0)`.

I think the best solution is to improve the error message that is shown by lps2lts. Maybe if the message gives some hints about a possible cause, that would help users a lot.

**Comment by wiegerw** [comment]
The type checker can easily detect that there is an ambiguity in the specification. And as a user I expect to be warned about that. IMO the lineariser has nothing to do with this problem.

**Comment by tneele** [comment]
Fundamentally, I don't see this specification as ambiguous: when the expression `i(s)` is typechecked with `Bool` as expected result, then it is natural that the function `i: S -> Bool` is the only candidate and is thus used. Of course, this is not clear to most users, so as @wiegerw suggests, a warning might be in place.

**Comment by wiegerw** [comment]
I would go much further: using the expression i(s) should simply not be allowed in this specification. Because it depends on the accidental content of the variable s whether or not this is a valid expression. Using that kind of code in a specification is very bad taste IMO.

**Comment by Valo13** [comment]
I believe that the choice of which `i` to use should not be made depending on the return type of all existing `i`, but depending on which `s` is provided, since `i` is only defined within the scope of `S1` and `S2`. As any `s` can be provided, any `i` can be expected and thus all `i` should be used correctly. In the given example this is not the case, since in `i(s) -> a . P()` `i` is required to return a boolean, whereas there exists an `i` on an `s` (namely `S1`) that does not return a boolean. During checking of the specification, the user should be (at least) warned about this.

All in all, as the error by lps2lts on this example gives an error about not being able to rewrite to the correct **type** (because it has the wrong type), the **type** checker should have (at least) warned the user about this.

**Comment by jgroote** [comment]
The problem is not related to state space generation, term rewriting and not even to structs.
The following specification is properly typed, and has essentially the same issue as
the original example. 

map eval:Int->Bool;
        eval:Int->Pos;

act a;
proc P(s: Int) = eval(s) -> a . P(s);
init P(0);

A very similar example from the standard data types is
map max:Nat#Nat->Nat;
        max:Pos#Pos->Pos;

If I inspect chapter 15.1 of the book, it allows the declarations above. 
Regarding struct, neither section 3.4 nor section B10 forbids the original example. 
The definition of what is or is not properly typed, remains an issue, and I hope that the work of Hendrik van Antwerpen will settle this problem in a definitive manner.

**Comment by jgroote** [comment]
Would the following warning be an acceptable solution in this case:

Warning. Projection function i occurs multiple times with different sorts in struct S1(i: Int) | S2(i: Bool).

**Comment by Valo13** [comment]
That would definitely be an improvement, but I'm afraid that this may be part of a bigger issue.
See the specification below, which ends up in the same "does not rewrite" error in lps2lts.

```
sort
  S = struct S1(j: Int)?isS1 | S2(i: Bool)?isS2;

act
  a;

proc
  P(s: S) = i(s) -> a.P();

init
  P(S1(0));
```

An `S1` is provided, but `S1` does not have any function `i`, so one could expect the checker to complain, but it says it's a valid specification. In my opinion, to be allowed to use `i` in the above process as it is, it should be defined for all `S`. But this might not always be necessary, for instance when the use of a projection function is guarded by the corresponding recognizer function such as `isS2(s) -> i(s) -> a.P()`. I can imagine that checking for correct projection function usage is rather complex, so maybe we should leave this bigger issue be for now.

All in all, I think that for this case that warning would be enough.

**Comment by Valo13** [comment]
I'm actually getting the feeling that incorrect use of projection functions may be something that can only be found in general during 'runtime' (when applying the semantics of the specification like in lps2lts, pbes2bool and pbessolve).

**Comment by jgroote** [comment]
Provide a warning in the typechecker if the problem occurs in a struct. If this warning is annoying it can easily be removed.
