### ISSUE TITLE
The GJKW branching bisimulation algorithm uses quite a lot of memory

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1462]
The GJKW branching bisimulation algorithm is quite memory hungry. In some cases it uses 5 times the amount of memory the classical GV algorithm is using.

It is suspected that this is due to the fact that within GJKW the transition system is first translated to a Kripke structure. This substantially increases the number of states.

It is possible to adapt the GJKW algorithm such that it works on labelled transition systems by "grouping" the incoming transitions on label. This technique is also used in the GRV strong bisimulation algorithm. This should reduce the memory requirements substantially, while maintaining the excellent performance of GJKW.

**Comment by tneele** [comment]
A new implementation, by David Jansen, that operates directly on LTSs is almost finished. We can consider to make that algorithm the standard in the next release.
