### ISSUE TITLE
Export vector graphics from statespaces in ltsgraph and ltsview.

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1465]
It would be useful to export a visualization of a statespace to a vector graphics format such as .svg (Scalable Vector Graphics) for use in papers and posters.  From the current export methods the bitmap export is similar to taking a screen shot and as such it is not scalable. The TikZ output is only available for ltsgraph, and it requires some additional work to make it usable. Furthermore this requires you to edit (possibly large) TikZ code instead of editing the output graphically. 

The old vector graphics export using gl2ps has been removed, because of issues with the library and the output was not satisfying. A hypothetical solution would be to generate the vector graphics information directly from the requested draw operation, i.e. draw node or edge, in a similar way that the TikZ output is implemented currently.

**Comment by FerryT** [comment]
Teaser: ![ltsgraphsvgwip](https://user-images.githubusercontent.com/1038465/64030525-0c3dbd00-cb47-11e9-8592-d49af2c4b6db.png)

**Comment by tneele** [comment]
@FerryT What is the state of your vector export prototype? I recently received a question about this feature, so it would be nice to reintroduce it in the next release.

**Comment by FerryT** [comment]
Yes, my intention is to have this done before the next release. Unfortunately, I do not have acces to my code base right now (due to the lock down). I'll soon try to get a hold to it so I can finish it. It really isn't all the much work anymore.
