### ISSUE TITLE
ltsgraph does not work on windows 10 on extended second screen with displaylink

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1467]
If a laptop running windows 10 is connected to a second screen using displaylink, ltsgraph does not work on the second screen if displays are extended.
In case the laptop screen is set as main screen, ltsgraph will work on the laptop screen but freezes when moved to the second screen. In case the second screen is set as main screen, ltsgraph only shows an empty white window, even when moved to the laptop screen.
Making the scaling and resolution the same for both screens does not solve this.

**Comment by mlaveaux** [comment]
This bug can be reproduced when ltsgraph is built from the latest commit (hash: eb33f6acf) with the following configuration:
- Qt version 5.11.1.
- Visual Studio 2017, version 15.7.
- Windows 10 64bit, build 1803.
- Display link driver version TBD.

Additional information: Dragging the white window to the other screen and forcing a refresh by toggling full screen restores the functionality. Now, when this window is dragged back it will stay frozen. However, it is possible to modify the buttons without the view updating. This can be witnessed by dragging the frozen window to the screen where it works and after a repaint the widgets will have changed. Finally, the buttons in the toolbar do work when the window is frozen, but not white.

**Comment by Valo13** [comment]
It can also be reproduced with Qt 5.6

**Comment by Valo13** [comment]
Sadly it doesn't

**Comment by mlaveaux** [comment]
I can no longer reproduce this issue after the extensive changes to ltsgraph (commit hash 6ecaf8c3c1714a7c2b3cb3cbcddf02bfe3a06f6a) to upgrade the rendering to a more modern OpenGL version. This was with both Qt 5.12.1 and 5.13, Visual Studio 2019 version 16.1 and Windows 10 1908.

**Comment by Valo13** [comment]
I can no longer repreduce this on the system I had this issue on (using Qt 5.9). However as Thomas can still reproduce this on one of his systems I will keep this issue open.

**Comment by FerryT** [comment]
Is this still an issue on Qt > 5.12 ?

**Comment by Valo13** [comment]
I can't test this as this requires access to my office in the metaforum since we use displaylink there.

**Comment by FerryT** [comment]
Ok, to be continued then, after lock-down :)

**Comment by mlaveaux** [comment]
I can no longer reproduce this issue with display link driver version 9.3.3324.0 using the mCRL2 202106.0 release and a locally compiled version. It also does not seem to be present on Olav's machine although it is different from the laptop on which the issue had been reported originally. Therefore, we consider this issue to be resolved.
