### ISSUE TITLE
pbesstategraph fails to simplify guards for source/target computation

### ISSUE THREAD

**Issue by jkeiren** [mCRL2org/mCRL2#1474]
It appears there is a problem in the development version of pbesstategraph.
When comparing the development version (bb7b1cb66bM) 
with the 201707.1 release, on the following example, there is a significant difference in the computation.

```
pbes
mu X(s,n:Nat) = (val(s == 1) && Z(2,n));
mu Z(s,n:Nat) = Z(s,n) && (val(s == 3) => Z(s,n+1));

init
X(1,2);
```
This example is attached to this issue as 
[bug.txt](https://github.com/mCRL2org/mCRL2/files/2286543/bug.txt).

To reproduce, execute the following for both the development and the release version:
```
txt2pbes bug.txt | pbesstategraph -d > /dev/null
```

The control flow parameters that are computed are the same in both cases:
```
[stategraph::verbose] --- computed control flow parameters ---
[stategraph::verbose] (Z, 0, s)
[stategraph::verbose] (X, 0, s)
```

According to the 201707.1 release, these control flow parameters can assume the following values
```
[stategraph::debug]   === computing values for the components
[stategraph::debug]   {(X, 0, s)} values = { 1 }
[stategraph::debug]   {(Z, 0, s)} values = { 3 }

```
The current development version of pbesstategraph (pbesstategraph —-version gives: 201707.1.bb7b1cb66bM (Release)) returns the following:
```
[stategraph::debug]   === computing values for the components
[stategraph::debug]   {(X, 0, s)} values = { 1 }
[stategraph::debug]   {(Z, 0, s)} values = {  }

```
The consequence is that the local control flow graph for the second component (with Z) in the old version looks like:
```
[stategraph::debug]   --- computed local control flow graph 1
[stategraph::debug]   (Z, 0, s=3) outgoing_edges: (Z, 0, s=3) (labels = { 1 })
[stategraph::debug]   (Z, 0, s=2) outgoing_edges:
[stategraph::debug]   (X, ?, ?=?) outgoing_edges: (Z, 0, s=2) (labels = { 0 })

```
and in the new version we get:
```
[stategraph::debug]   --- computed local control flow graph 1
[stategraph::debug]   (Z, 0, s=2) outgoing_edges:
[stategraph::debug]   (X, ?, ?=?) outgoing_edges: (Z, 0, s=2) (labels = { 0 })
```

From this point on the computations diverge further.

Let’s investigate this the cause of this difference a bit further. This seems to be caused by the lack of source and target information for the equation for Z.
In the release version of the tool we find:
```
[stategraph::debug]   equation = mu Z(s,n: Nat) = Z(s, n) && (val(!(s == 3)) || Z(s, n + 1))
[stategraph::debug]       predvar[0] = Z(s, n) guard = true
[stategraph::debug]           sigma = []
[stategraph::debug]           copy(Z, 0, 0) = 0
[stategraph::debug]           copy(Z, 0, 1) = 1
[stategraph::debug]           used    = {  }
[stategraph::debug]           changed = {  }
[stategraph::debug]       predvar[1] = Z(s, n + 1) guard = s == 3
[stategraph::debug]           source(Z, 1, 0) = 3
[stategraph::debug]           sigma = [s := 3]
[stategraph::debug]           target(Z, 1, 0) = 3
[stategraph::debug]           copy(Z, 1, 0) = 0
[stategraph::debug]           used    = { 0 }
[stategraph::debug]           changed = { 1 }
```

In the development version, instead we get:
```
[stategraph::debug]   equation = mu Z(s,n: Nat) = Z(s, n) && (val(!(s == 3)) || Z(s, n + 1))
[stategraph::debug]       predvar[0] = Z(s, n) guard = true
[stategraph::debug]           sigma = []
[stategraph::debug]           copy(Z, 0, 0) = 0
[stategraph::debug]           copy(Z, 0, 1) = 1
[stategraph::debug]           used    = {  }
[stategraph::debug]           changed = {  }
[stategraph::debug]       predvar[1] = Z(s, n + 1) guard = !(s != 3)
[stategraph::debug]           sigma = []
[stategraph::debug]           copy(Z, 1, 0) = 0
[stategraph::debug]           used    = { 0 }
[stategraph::debug]           changed = { 1 }

```
Most notably, in the development version, the information 
```
[stategraph::debug]           source(Z, 1, 0) = 3
[stategraph::debug]           sigma = [s := 3]
[stategraph::debug]           target(Z, 1, 0) = 3
```
for the second PVI in the equation for Z is missing.

As far as I can see, this is caused by a difference in the guard that is used for this PVI. In the original, the guard is s == 3, whereas in the development version the guard is !(s != 3).

My suspicion is that, somehow, there is a regression in the call to simplify() on line 915 in include/mcrl2/pbes/stategraph_algorithm.h which should reduce the pbes to a form appropriate for computing the guard.

**Comment by tneele** [comment]
Thanks for the report. There was indeed a problem in the stategraph simplifier. It should be fixed now.

**Comment by jkeiren** [comment]
Thanks, I can confirm the issue has been fixed.
