### ISSUE TITLE
Use the lts library for counter-examples in ltscompare

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1481]
A trc file generated by ltscompare cannot be opened in lpsxsim.

**Comment by tneele** [comment]
The traces generated by ltscompare are lacking state information. Therefore, it's currently not possible to load these traces in lpsxsim. The best alternative for now it to use the tool tracepp.

**Comment by tneele** [comment]
After some discussion in the most recent meeting, we agreed that this issue should be addressed with a more general solution. In short: the toolset currently contains various algorithms that construct some kind of evidence (counter-example or witness). This evidence can have different shapes, not just traces. The best solution is therefore to retire the trace library and rely solely on the lts library for evidence.
