### ISSUE TITLE
Enumerator sometimes behaves differently for Nat and Int types

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1486]
The following code works fine with Nat but not in case if we replace each Nat with Int. (total 6 replacements)
```
act
  send1,send2,transfer1, transfer2:Nat;
  rcv1,rcv2:Nat;
  showValues:Nat#Nat;
proc
  P1 = send1(20).send2(25);
  P2 = sum x:Nat.rcv1(x).sum y:Nat.rcv2(y+x).showValues(x,y);
init
  allow({transfer1, transfer2,showValues},
    comm({send1|rcv1->transfer1, send2|rcv2->transfer2},
      P1||P2
  ));
```

With Int it works only if we use `send1(0)` in P1 process.

**Comment by matifch** [comment]
for y+x and y-x it doesn't work with Int type but for y*x, it is OK with both Int and Nat

**Comment by tneele** [comment]
For reference, the following commands in `mcrl2i` illustrate the problem:
```
mCRL2 interpreter (type h for help)
? s y:Nat . y + 1 == 1
[y := 0] evaluates to true
? s y:Int . y + 20 == 25
[y := 5] evaluates to true
enumeration was aborted, since it did not complete within 10000 iterations
? s y:Int . y + 1 == 1
[y := 0] evaluates to true
enumeration was aborted, since it did not complete within 10000 iterations
```
Maybe someone can investigate why the enumerator behaves differently for `Nat` and `Int`.

**Comment by tneele** [comment]
This problem can be resolved by replacing the rewrite rules
```
pred(@c1) = @c0;
pred(@cDub(true,p)) = @cNat(@cDub(false,p));
pred(@cDub(false,p)) = @dub(true,pred(p));
```
with
```
pred(@c1) = @c0;
pred(@cDub(b,p)) = @cNat(if(b,@cDub(false,p),@dub2(pred(p))));
@dub2(@c0) = @c1;
@dub2(@cNat(p)) = @cDub(true,p);
```
Where `@dub2` is a new mapping of sort `Nat  -> Pos`. Since `@dub` is always used with the boolean parameter `true` in `pred`, its equations can be optimised, and the constructor `@cNat` can be pulled outwards, which helps the enumerator.
