### ISSUE TITLE
mcrl2ide does not start from mcrl2-gui

### ISSUE THREAD

**Issue by jkeiren** [mCRL2org/mCRL2#1487]
Observed behaviour:
When starting mcrl2-gui, and then selecting `Open mcrl2ide' from the context menu, mcrl2ide does not start.

Expected behaviour:
mcrl2ide should start when performing the described actions.

Additional info:
When inspecting the contents of the package (from Finder, right click on mCRL2.app > Show package contents), it is clear that the mcrl2ide binary is present (Contents/bin/mcrl2ide), and starting it from that location by double clicking correctly starts mcrl2ide.

Operating System: macOS 10.13.6
mCRL2 version: 201808.0

**Comment by Valo13** [comment]
We are not able to reproduce this (neither on Windows, Mac or Linux). The problem could be that it is not able to find the executable of mcrl2ide. Is the mcrl2ide executable in the working directory of mcrl2-gui or is mcrl2ide's containing folder added to PATH?

**Comment by Valo13** [comment]
As we have a number of failing builds due to tests right now it's best to compile the tools locally.

**Comment by Valo13** [comment]
I have tested this with Jan Friso and mcrl2ide now opens correctly from mcrl2-gui. However, then the same problem occurs for mcrl2ide, namely that it cannot find the executables it needs since they are referred to using a relative path.

**Comment by Valo13** [comment]
Commit a224058f08bd6a8e246d27b9bdbd73f5957ae1cf should have fixed what was mentioned in the above comment.
