### ISSUE TITLE
ltsconvert does not preserve spaces in labels of .aut files

### ISSUE THREAD

**Issue by wiegerw** [mCRL2org/mCRL2#1492]
When applying `ltsconvert 1.aut 2.aut` to 1.aut:

```
des (0,1,2)
(0,"x y",1)
```

the result (2.aut) is

```
des (0,1,2)
(0,"xy",1)
```

This is quite unexpected.

**Comment by jgroote** [comment]
Dag Wieger,

Dit is inderdaad een hele rare fout.

Jan Friso

des (0,1,2)
(0,"x y",1)

the result (2.aut) is

des (0,1,2)
(0,"xy",1)




> On 21 Oct 2018, at 23:15, Wieger Wesselink <notifications@github.com> wrote:
> 
> Assigned #1492 to @jgroote.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

____________________________________________________________________________________
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by jgroote** [comment]
Resolved in revision d5ed20c52400b625ce7903237c99afeecf7b4106 also indicated directly above this comment.
