### ISSUE TITLE
When the dist operator is preceded by an action, distribution variables are unusable

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1495]
When the dist operator is (syntactically) preceded by an action, the variables declared in the `dist` operator are not rewritten. Examples:
When creating a PLTS (Probabilistic LTS) of the following specification:
```
act r:Bool;
init dist b:Bool [1/2].r(b);
```
the PLTS contains transitions `r(true)` and `r(false)` as expected. However, when creating a PLTS of the following specification:
```
act a;
    r:Bool;
init a.dist b:Bool [1/2].r(b);
```
the PLTS contains the action `r(b)` instead.

Similarly, when creating a PLTS of the following specification:
```
act t, f;
init dist b:Bool [1/2].(b) -> t <> f;
```
the PLTS is as expected (a probabilistic choice between `t` and `f`). However, when creating a PLTS of the following specification:
```
act a, t, f;
init a.dist b:Bool [1/2].(b) -> t <> f;
```
it gives the following error: 
```
[error]   Error while exploring state space: Expression !b does not rewrite to true or false in the condition s1 == 1 && !b
```

When the preceding action is moved to a different process however, as in the below two specifications, the PLTS is generated correctly:
```
act a;
    r:Bool;
proc X = a.Y;
     Y = dist b:Bool [1/2].r(b);
init X;
```
```
act a, t, f;
proc X = a.Y;
     Y = dist b:Bool [1/2].(b) -> t <> f;
init X;
```

**Comment by tneele** [comment]
This is a bug in the lineariser. For the specification
```
act a;
    r:Bool;
init a.dist b:Bool [1/2].r(b).delta;
```
the lineariser produces
```
act  a;
     r: Bool;

proc P(s1: Pos) =
       (s1 == 2) ->
         a .
         dist b: Bool[1 / 2] .
         P(s1 = 1)
     + (s1 == 1) ->
         r(b) .
         P(s1 = 3)
     + delta;

init P(2);
```
The variable `b` which is bound by the dist operator should be stored in a process parameter.
