### ISSUE TITLE
Counterexamples generated by ltscompare do not have a consistent format

### ISSUE THREAD

**Issue by georgekie** [mCRL2org/mCRL2#1500]
Hi,
The trace file produced when using the -c option on ltscompare is garbled when using failures and is fine when using bisimulation equivalence.
ltscompare  -ebisim  -c i2.lts i1.lts
produces:
The default bisimulation comparison algorithm cannot generate counter examples. Therefore the slower gv algorithm is used instead.
Saved counterexample to: "Counterexample0.trc"
the resultant trace file is:-
a
tau

for failures divergence:
ltscompare  -pfailures  -c i2.lts i1.lts
The LTS in i2.lts is not included in the LTS in i1.lts (using failures refinement).
(note no mention of the trace file)
produces the following counter example file:
mCRL2Trace^A^@^@<8b>¯<83>^D
^Aa^@^A^L<empty_list>^@^A^EActId^B^A^A^@^A^A^FAction^B^A^A^B^A^A^R<list_constructor>^B^B^B^C    ^A^A^O@undefined_real^@^A^DReal^@^A^FSortId^A^A^A^F^PDataVarIdNoIndex^B^A^A^E^A^G^Dpair^B^A^A^D^A^H^D<80>

Using the latest nightly build.
ltscompare mCRL2 toolset 201808.0.b05b7d3e4f (Release)
Copyright (c) 2018 Technische Universiteit Eindhoven.
This is free software.  You may redistribute copies of it under the
terms of the Boost Software License <http://www.boost.org/LICENSE_1_0.txt>.
There is NO WARRANTY, to the extent permitted by law.

George Kielty

**Comment by jgroote** [comment]
You can print the counterexample using tracepp.


Jan Friso Groote
www.win.tue.nl/~jfg<http://www.win.tue.nl/~jfg>

On 24 Nov 2018, at 21:17, georgekie <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
The trace file produced when using the -c option on ltscompare is garbled when using failures and is fine when using bisimulation equivalence.
ltscompare -ebisim -c i2.lts i1.lts
produces:
The default bisimulation comparison algorithm cannot generate counter examples. Therefore the slower gv algorithm is used instead.
Saved counterexample to: "Counterexample0.trc"
the resultant trace file is:-
a
tau

for failures divergence:
ltscompare -pfailures -c i2.lts i1.lts
The LTS in i2.lts is not included in the LTS in i1.lts (using failures refinement).
(note no mention of the trace file)
produces the following counter example file:
mCRL2Trace^A^@^@<8b>¯<83>^D
^Aa^@^A^L<empty_list>^@^A^EActId^B^A^A^@^A^A^FAction^B^A^A^B^A^A^R<list_constructor>^B^B^B^C ^A^A^O@undefined_real^@^A^DReal^@^A^FSortId^A^A^A^F^PDataVarIdNoIndex^B^A^A^E^A^G^Dpair^B^A^A^D^A^H^D<80>

Using the latest nightly build.
ltscompare mCRL2 toolset 201808.0.b05b7d3e4f (Release)
Copyright (c) 2018 Technische Universiteit Eindhoven.
This is free software. You may redistribute copies of it under the
terms of the Boost Software License http://www.boost.org/LICENSE_1_0.txt.
There is NO WARRANTY, to the extent permitted by law.

George Kielty

**Comment by tneele** [comment]
Significant changes in ltscompare are required to produce consistent evidence files, as detailed in issue #1481. I will close this issue, any further comments should go into the aforementioned issue.
