### ISSUE TITLE
PBESs produced by pbesinst cannot be read by txt2pbes

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1508]
The tool `pbesinst` can produce predicate variables that contain an '@' symbol in their name. This leads to parsing errors in `txt2pbes`.

**Steps to reproduce**
Save the following in a file called test.txt:
```
pbes nu X(b:Bool) = X(!b);
init X(true);
```
Execute these commands:
```
txt2pbes test.txt test.pbes
pbesinst -sfinite --select="*(*:Bool)" test.pbes test.inst.pbes
pbespp test.inst.pbes test.inst.txt
txt2pbes test.inst.txt test.inst.pbes
```
Expected result: the PBES in ASCII format is parsed correctly.
Actual result: the following exception is thrown.
```
[parser::error]   Line 1, column 9: syntax error after 'X'
[parser::error]     pbes nu X@false =
[parser::error]              ^
[parser::error]   Unexpected '@'
[error]   syntax error
```

**Comment by wiegerw** [comment]
This naming scheme was chosen intentionally. It has a clear purpose, and I don't think it should be changed / removed.

Of course an alternative naming scheme can be added.

**Comment by tneele** [comment]
I agree, the naming scheme is useful. However, unless I'm missing something, changing each @ to an underscore would not significantly change the functionality of the naming scheme.

An alternative solution would be to change the parser, and allow @ symbols in identifiers, but I find it hard to estimate what the impact of such a change would be.

**Comment by wiegerw** [comment]
Changing @ to underscore will create ambiguities, so I am not in favor of that.

I'm pretty sure that allowing @ symbols in identifiers will create problems, since how can you tell if a@b is a name or a binary expression.
