### ISSUE TITLE
Alphabet reduction over a simple sequential process fails

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1519]
Consider the following specification:
```
act a,b;
init allow({a}, a.b.delta);
```
Save it in `test.mcrl2` and run the commands
```
mcrl22lps test.mcrl2 test.lps
lps2lts test.lps test.lts
ltsgraph test.lts
```
Expected result: the state space contains a single trace `a`.
Actual result: there is a single trace `a.b`.
This seems to be a problem with alphabet reduction, as the action `b` is present in the linear process.

**Comment by jgroote** [comment]
The problem disappears when the flag -z is used in the lineariser. 
This indeed suggests a problem with the alphabet conversion. 
Hence, I assigned it to Wieger.
