### ISSUE TITLE
LPS generator reports 'error while exploring state space' due to internal divisions through 0

### ISSUE THREAD

**Issue by BitVortex** [mCRL2org/mCRL2#1521]
When using the sum operator with bounds, the LPS generator internally seems to use logic that causes rewrites of the formula incorporating `mod 100`, which can lead to divisions by 0 and thus a failure to explore the state space.

Here's the current specification:
```
act r: Real;

proc P = sum v1raw, v2raw: Nat, v1e, v2e: Int .
         ((v1raw/100 + v1e/100) >= 0 && (v1raw/100 + v1e/100) <= 105/10 &&
          (v2raw/100 + v2raw/100 * v2e/100) >= 0 && (v2raw/100 + v2raw/100 * v2e/100) <= 105/10)
         -> r((v1raw/100 + v1e/100) + (v2raw/100 + v2raw/100 * v2e/100)) . P;

init P;
```

And the error reported by `mcrl22lps.exe`:
> [error]   Error while exploring state space: Expression 0 <= 0 + 0 / 0 / 100 && 0 + 0 / 0 / 100 <= 21 / 2 does not rewrite to true or false in the condition 0 <= v1raw_P div 100 + v1raw_P mod 100 / 100 + v1e_P div 100 + v1e_P mod 100 / 100 && v1raw_P div 100 + v1raw_P mod 100 / 100 + v1e_P div 100 + v1e_P mod 100 / 100 <= 21 / 2 && 0 <= v2raw_P div 100 + v2raw_P mod 100 / 100 + v2raw_P / 100 * v2e_P / 100 && v2raw_P div 100 + v2raw_P mod 100 / 100 + v2r...

**Comment by jgroote** [comment]
There are actually two problems with this specification.
You write

   sum v1raw, v2raw: Nat, v1e, v2e: Int ……

This leads to the enumeration of all integers. As there are an infinite number of them, state space generation will never stop. 
It cannot even generate the outgoing transitions of the first state. If you want a state space you should add explicit lower and
upper bounds for the enumerated integers. 

The second problem is that an expression v2raw/100 * v2e/100 is parsed as (v2raw /(100 *( v2e / 100))). Putting 
explicit brackets around it takes care that parsing is done as expected. 

It should be investigated what the desired parsing of v2raw/100 * v2e/100 should be.

**Comment by jgroote** [comment]
There are actually two problems with this specification.
You write
   
    sum v1raw, v2raw: Nat, v1e, v2e: Int ……

This leads to the enumeration of all integers. As there are an infinite number of them, state space generation will never stop. 
It cannot even generate the outgoing transitions of the first state. If you want a state space you should add explicit lower and
upper bounds for the enumerated integers. 

The second problem is that an expression v2raw/100 * v2e/100 is parsed as (v2raw /(100 *( v2e / 100))). Putting 
explicit brackets around it takes care that parsing is done as expected. 

It should be investigated what the desired parsing of v2raw/100 * v2e/100 should be. 


   

> On 18 Feb 2019, at 21:28, BitVortex <notifications@github.com> wrote:
> 
> When using the sum operator with bounds, the LTS generator internally seems to use logic that causes rewrites of the formula incorporating mod 100, which can lead to divisions by 0 and thus a failure to explore the state space.
> 
> Here's the current specification:
> 
> act r: Real;
> 
> proc P = sum v1raw, v2raw: Nat, v1e, v2e: Int .
>          ((v1raw/100 + v1e/100) >= 0 && (v1raw/100 + v1e/100) <= 105/10 &&
>           (v2raw/100 + v2raw/100 * v2e/100) >= 0 && (v2raw/100 + v2raw/100 * v2e/100) <= 105/10)
>          -> r((v1raw/100 + v1e/100) + (v2raw/100 + v2raw/100 * v2e/100)) . P;
> 
> init P;
> 
> And the error reported by mcrl22lps.exe:
> 
> [error] Error while exploring state space: Expression 0 <= 0 + 0 / 0 / 100 && 0 + 0 / 0 / 100 <= 21 / 2 does not rewrite to true or false in the condition 0 <= v1raw_P div 100 + v1raw_P mod 100 / 100 + v1e_P div 100 + v1e_P mod 100 / 100 && v1raw_P div 100 + v1raw_P mod 100 / 100 + v1e_P div 100 + v1e_P mod 100 / 100 <= 21 / 2 && 0 <= v2raw_P div 100 + v2raw_P mod 100 / 100 + v2raw_P / 100 * v2e_P / 100 && v2raw_P div 100 + v2raw_P mod 100 / 100 + v2r...
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by tneele** [comment]
@BitVortex Did you manage to resolve the issue using the comments from @jgroote?

**Comment by BitVortex** [comment]
Yes, using bounds for the enumerated integers and explicit brackets to force correct parsing fixed the issue.
