### ISSUE TITLE
Polishing new LTSGraph implementation

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1531]
Remaining tasks to achieve feature parity (check mark means fixed):

- [x] Additional features for rendering nodes, transparency and probabilistic nodes.
- [x] In exploration mode and 2D view the nodes are placed in three dimensions when the layout algorithm is disabled.

Further enhancements:
- [ ] Labels could be rendered at their actual 3D position.
- [ ] The thickness of transitions and node borders could be increased (or a setting).
- [ ] All animation related things (and selection decaying) should be time dependent and not dependent on the frames per second for more consistency.
- [ ] Improving the UI of the visualisation pane.
- [ ] Adding a setting to control the projection (isometric or geometric).
- [x] Dragging the camera appear to have a constant effect on distance moved.
- [ ] Render distance should be increased. 
- [x] Switching between 3D and 2D should not reset the camera in all cases.
- [x] Adding some UI for hints on the controls (ctrl + drag for translation, shift+drag for rotation etc).

Remaining bugs:

- [ ] Nodes sometimes jump into the screen when trying to select something after zooming in in 3D mode.
- [ ] Locking a state in place while dragging it causes all adjacent transition handles and labels to be locked in place as well. To fix this behaviour every handle needs to be unlocked twice and every label unlocked once.
- [x] ~~The current implementation causes mysterious issues under Qt 5.5. Here, it crashes inside the drawText() function of QPainter when drawing labels, but even without labels nothing appears on the screen~~. The minimally supported version was changed to Qt 5.9 LTS which solves this issue and a warning should pop up when attempting to run ltsgraph using libraries below Qt 5.9. Unfortunately, compilation under Qt 5.5 must be preserved.

**Comment by tneele** [comment]
On top of the tasks listed above, there are also several issues that I experience on my own machine that need to be looked in to.

- [ ] A lot of warnings of the form `qt.glx: qglx_findConfig: Failed to finding matching FBConfig (8 8 8 1)`. This is probably related to anti-aliasing.
- [ ] The UI does not redraw when clicking buttons etc. Redraws only occur when the layout engine is running or when hovering over a node.

**Comment by mlaveaux** [comment]
These enhancements have been converted to an LTSgraph specific 'project' in GitHub and as such this issue is no longer needed to track progress on them. The current implementation contains all features of LTSgraph before the rendering rewrite except for certain animations which have been dropped as a feature.
