### ISSUE TITLE
Stochastic linearization produces incorrect distributions.

### ISSUE THREAD

**Issue by wiegerw** [mCRL2org/mCRL2#1536]
When linearizing the specification below, the resulting LPS has initial state `init dist b2,x3,x4,x5: Bool[1 * if(x3, 1 / 4, 3 / 4) * (1 / 2) * if(x5, 1 / 4, 3 / 4)] . P(3, 4, 3);`. This looks incorrect, since the probabilities sum up to 2.

```
act
  a,c,b,d;

proc
  P = b;
  Q = sum b1: Bool. ((dist x0: Bool[if(x0,1/4,3/4)].((x0) -> (dist x1: Bool[1/2].((x1) -> (c))))) . (c));
  R = dist x2: Bool[if(x2,1/4,3/4)].((x2) -> ((a) + (b)));

init
  block({b}, comm({c | c -> b}, allow({a, c, a | d, d}, (hide({a}, (P) || (Q))) || (R))));
```

**Comment by jgroote** [comment]
This problem should be resolved now.
