### ISSUE TITLE
ceil and sqrt

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1538]
The following expression is supposed to return 4 but it gives 3. 
ceil(sqrt(10))

2ndly the above expression cannot be used in function definition. For example, the following is an error for type checker but not the above if used in some action.

map 
 distance: Int#Int#Int#Int -> Nat;
 squareOfMinus: Int # Int -> Int;
var 
 x1,x2,y1,y2,a,b:Int;
eqn 
 distance(x1,x2,y1,y2) = ceil(sqrt(Int2Nat(x+y))) whr x=squareOfMinus(x1,x2), y=squareOfMinus(y1,y2) end;
 squareOfMinus (a,b)= minus*minus whr minus=(a-b) end;

**Comment by jgroote** [comment]
Hello Muhammad,

The natural square root of m is defined to be the largest natural number n such that n^2<=m.
This means that the square root of 3 is 1, 4 is 2, 5 is 2, 6 -> 2, … sqrt(9)=3, sqrt(10)=3.
In particular ceil(sqrt(10))=3.

If you would like to have k digits after the comma of sqrt(m), you could calculate
sqrt(m*10^2k)/10^k.  This is a real number. 

Regards, Jan Friso

> On 13 Jun 2019, at 10:56, matifch <notifications@github.com> wrote:
> 
> The following expression is supposed to return 4 but it gives 3.
> ceil(sqrt(10))
> 
> 2ndly the above expression cannot be used in function definition. For example, the following is an error for type checker but not the above if used in some action.
> 
> map
> distance: Int#Int#Int#Int -> Nat;
> squareOfMinus: Int # Int -> Int;
> var
> x1,x2,y1,y2,a,b:Int;
> eqn
> distance(x1,x2,y1,y2) = ceil(sqrt(Int2Nat(x+y))) whr x=squareOfMinus(x1,x2), y=squareOfMinus(y1,y2) end;
> squareOfMinus (a,b)= minus*minus whr minus=(a-b) end;
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by matifch** [comment]
Thanks Sir! for the quick reply and it works fine now. Please also comment on the type-checker's problem in line 7 of the following specification where ceil and sqrt are not allowed together. 

1. map
2.  distance: Int#Int#Int#Int -> Nat;
3.  squareOfMinus: Int # Int -> Int;
4.  var
5.  x1,x2,y1,y2,a,b:Int;
6.  eqn
7.  distance(x1,x2,y1,y2) = ceil(sqrt(Int2Nat(x+y))) whr x=squareOfMinus(x1,x2), y=squareOfMinus(y1,y2) end;
8.  squareOfMinus (a,b)= minus*minus whr minus=(a-b) end;

**Comment by tneele** [comment]
`ceil` is a function from Real to Int, while the return type of `sqrt` is Nat. I think you should just leave out the `ceil`, so the specification becomes
```
map
distance: Int#Int#Int#Int -> Nat;
squareOfMinus: Int # Int -> Int;
var
x1,x2,y1,y2,a,b:Int;
eqn
distance(x1,x2,y1,y2) = sqrt(Int2Nat(x+y)) whr x=squareOfMinus(x1,x2), y=squareOfMinus(y1,y2) end;
squareOfMinus (a,b)= minus*minus whr minus=(a-b) end;
```

**Comment by jgroote** [comment]
This is indeed the problem. ceil yields an Int, but distance requires as result type Nat.
Int cannot automatically be translated to Nat. You should either leave out ceil, or add
an extra Int2Nat conversion, but this last construct is a little ugly.

Regards, Jan Friso 


> On 13 Jun 2019, at 14:14, Thomas Neele <notifications@github.com> wrote:
> 
> ceil is a function from Real to Int, while the return type of sqrt is Nat. I think you should just leave out the ceil, so the specification becomes
> 
> map
> distance: Int#Int#Int#Int -> Nat;
> squareOfMinus: Int # Int -> Int;
> var
> x1,x2,y1,y2,a,b:Int;
> eqn
> distance(x1,x2,y1,y2) = sqrt(Int2Nat(x+y)) whr x=squareOfMinus(x1,x2), y=squareOfMinus(y1,y2) end;
> squareOfMinus (a,b)= minus*minus whr minus=(a-b) end;
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128
