### ISSUE TITLE
Stochastic linearization causes segmentation fault

### ISSUE THREAD

**Issue by wiegerw** [mCRL2org/mCRL2#1539]
The following minimized example leads to an error in the function transform_initial_distribution_term. Found using random testing.

```act  a,c,b,d;

proc P = (true -> delta <> (dist x0: Bool[1 / 2] . x0 -> a)) . P;

init P;
```

**Comment by jgroote** [comment]
Dag WIeger,

Opgelost. 

Groet en dank, Jan Friso 

> On 14 Jun 2019, at 10:23, Wieger Wesselink <notifications@github.com> wrote:
> 
> The following minimized example leads to an error in the function transform_initial_distribution_term. Found using random testing.
> 
> 
> proc P = (true -> delta <> (dist x0: Bool[1 / 2] . x0 -> a)) . P;
> 
> init P;
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128
