### ISSUE TITLE
Alternative Version of the Alternating Bit Protocol

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1540]
I developed a version of ABP different from the one given in examples of mCRL2. I used one channel assuming that the channel transmits data from the source to the receiver and transmit bit value from the receiver to transmitter but at a time there's one way traffic.
Please comment w.r.t. pros and cons of both versions where both have the same number of states and transitions and they are given below:
My Version:
```
sort
D     = struct d1 | d2;

Channel_message= struct msg(data:D, bit:Bool)| bit_msg(bit:Bool)?isBit_msg|nAck|msg_lost; 

act

useMessage, getFromSource:D;
rcvAtChannel, send2Channel, transfer2Channel, rcvFromChannel, send2Process, transferFromChannel:Channel_message;
i;

proc
Sender(b:Bool)     = sum d:D. getFromSource(d).Transmitter(d,b);
Transmitter(d:D,b:Bool) = send2Channel(msg(d,b)).( rcvFromChannel(bit_msg(b)).Sender(!b)+
                                                                                ( rcvFromChannel(bit_msg(!b))+rcvFromChannel(nAck)
                                                                                 ).Transmitter(d,b));

Receiver(rcvd_bit:Bool)=  sum d:D.rcvFromChannel(msg(d,rcvd_bit)).useMessage(d).send2Channel(bit_msg(rcvd_bit)).Receiver(!rcvd_bit)
                         +
                          (sum d:D.rcvFromChannel(msg(d,!rcvd_bit))+rcvFromChannel(msg_lost)).send2Channel(bit_msg(!rcvd_bit)).Receiver(rcvd_bit);
Channel      = sum m:Channel_message.rcvAtChannel(m).(i.send2Process(m)+i.(isBit_msg(m)->send2Process(nAck)<>send2Process(msg_lost) )).Channel;

init
hide({i},
allow({transfer2Channel,i,transferFromChannel, useMessage, getFromSource},
comm({rcvAtChannel|send2Channel->transfer2Channel, 
      rcvFromChannel|send2Process-> transferFromChannel},
Sender(true) || Channel || Receiver(true)
)
)
);
%%%%%%%%%%%%%%%% The End %%%%%%%%%

The Version in examples is:
sort
D     = struct d1 | d2;
Error = struct e;

act
r1,s4: D;
s2,r2,c2: D # Bool;
s3,r3,c3: D # Bool;
s3,r3,c3: Error;
s5,r5,c5: Bool;
s6,r6,c6: Bool;
s6,r6,c6: Error;
i;

proc
S(b:Bool)     = sum d:D. r1(d).T(d,b);
T(d:D,b:Bool) = s2(d,b).( r6(b).S(!b) + 
                                        (
                                          r6(!b)+r6(e)
                                        ).T(d,b)
                        );

R(b:Bool)     = sum d:D. r3(d,b).s4(d).s5(b).R(!b)+
(sum d:D.r3(d,!b)+r3(e)).s5(!b).R(b);

K             = sum d:D,b:Bool. r2(d,b).(i.s3(d,b)+i.s3(e)).K;

L             = sum b:Bool. r5(b).(i.s6(b)+i.s6(e)).L;

init
hide({i},
allow({r1,s4,c2,c3,c5,c6,i},
comm({r2|s2->c2, r3|s3->c3, r5|s5->c5, r6|s6->c6},
S(true) || K || L || R(true)
)
)
);
```

**Comment by jgroote** [comment]
Hello Muhammad,

I think our description is equivalent to the classical description. There is one potential difficulty, namely that messages sent at one side 
can in principle be receive at the same side. That does not go wrong in your case  because you send a bit into one direction and 
full message in the other. But maybe you should add an address of the receiver to your channel message type.

Regards, Jan Friso 

> On 16 Jun 2019, at 16:05, matifch <notifications@github.com> wrote:
> 
> I developed a version of ABP different from the one given in examples of mCRL2. I used one channel assuming that the channel transmits data from the source to the receiver and transmit bit value from the receiver to transmitter but at a time there's one way traffic.
> Please comment w.r.t. pros and cons of both versions where both have the same number of states and transitions and they are given below:
> My Version:
> sort
> D = struct d1 | d2;
> 
> Channel_message= struct msg(data:D, bit:Bool)| bit_msg(bit:Bool)?isBit_msg|nAck|msg_lost;
> 
> act
> 
> useMessage, getFromSource:D;
> rcvAtChannel, send2Channel, transfer2Channel, rcvFromChannel, send2Process, transferFromChannel:Channel_message;
> i;
> 
> proc
> Sender(b:Bool) = sum d:D. getFromSource(d).Transmitter(d,b);
> Transmitter(d:D,b:Bool) = send2Channel(msg(d,b)).( rcvFromChannel(bit_msg(b)).Sender(!b)+
> ( rcvFromChannel(bit_msg(!b))+rcvFromChannel(nAck)
> ).Transmitter(d,b));
> 
> Receiver(rcvd_bit:Bool)= sum d:D.rcvFromChannel(msg(d,rcvd_bit)).useMessage(d).send2Channel(bit_msg(rcvd_bit)).Receiver(!rcvd_bit)
> +
> (sum d:D.rcvFromChannel(msg(d,!rcvd_bit))+rcvFromChannel(msg_lost)).send2Channel(bit_msg(!rcvd_bit)).Receiver(rcvd_bit);
> Channel = sum m:Channel_message.rcvAtChannel(m).(i.send2Process(m)+i.(isBit_msg(m)->send2Process(nAck)<>send2Process(msg_lost) )).Channel;
> 
> init
> hide({i},
> allow({transfer2Channel,i,transferFromChannel, useMessage, getFromSource},
> comm({rcvAtChannel|send2Channel->transfer2Channel,
> rcvFromChannel|send2Process-> transferFromChannel},
> Sender(true) || Channel || Receiver(true)
> )
> )
> );
> %%%%%%%%%%%%%%%% The End %%%%%%%%%
> 
> The Version in examples is:
> sort
> D = struct d1 | d2;
> Error = struct e;
> 
> act
> r1,s4: D;
> s2,r2,c2: D # Bool;
> s3,r3,c3: D # Bool;
> s3,r3,c3: Error;
> s5,r5,c5: Bool;
> s6,r6,c6: Bool;
> s6,r6,c6: Error;
> i;
> 
> proc
> S(b:Bool) = sum d:D. r1(d).T(d,b);
> T(d:D,b:Bool) = s2(d,b).( r6(b).S(!b) +
> (
> r6(!b)+r6(e)
> ).T(d,b)
> );
> 
> R(b:Bool) = sum d:D. r3(d,b).s4(d).s5(b).R(!b)+
> (sum d:D.r3(d,!b)+r3(e)).s5(!b).R(b);
> 
> K = sum d:D,b:Bool. r2(d,b).(i.s3(d,b)+i.s3(e)).K;
> 
> L = sum b:Bool. r5(b).(i.s6(b)+i.s6(e)).L;
> 
> init
> hide({i},
> allow({r1,s4,c2,c3,c5,c6,i},
> comm({r2|s2->c2, r3|s3->c3, r5|s5->c5, r6|s6->c6},
> S(true) || K || L || R(true)
> )
> )
> );
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128
