### ISSUE TITLE
data_specification::equations() can contain duplicates

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1543]
The function data_specification::equations() returns a vector of equations defined in that specification. One would expect that this vector does not contain duplicates. This situation can occur, however, as demonstrated by the following code:
```C++
#include "mcrl2/data/data_specification.h"
#include "mcrl2/data/parse.h"

using namespace mcrl2;

int main(int /*argc*/, char** /*argv*/)
{
  data::data_specification data_spec = data::parse_data_specification("sort Bit = struct b0 | b1;");
  for(std::size_t i = 0; i < data_spec.equations().size(); i++)
  {
    for(std::size_t j = 0; j < i; j++)
    {
      if(data_spec.equations()[i] == data_spec.equations()[j])
      {
        std::cout << "Duplicate equation! " << data_spec.equations()[i] << std::endl;
      }
    }
  }

  return 0;
}
```
The code can be run easily by pasting it in `libraries/data/example/example5.cpp`, rerunning cmake and compiling and running the new target `example_data_example5`.
If this is not a bug, then I would be interested to know what the rationale behind this 'feature' is.

**Comment by tneele** [comment]
@jgroote Can you review commit 4e09591c2? If you agree with the changes, I will close this ticket.

**Comment by jgroote** [comment]
I did not like commit 4e09591 as it uses a linear insert. As an alternative I replaced the vector of equations by a set of equations.
