### ISSUE TITLE
Recent changes in alphabet conversions brake lpsconstelm and lpssumelm

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1554]
A recent change in the alphabetconversions causes a copy to be made of the 
process in the initial state. Very much simplified:

act a:Nat;
proc P = sum n:Nat.a(n).P;
init P;

is translated by the alphabet conversion into

proc P=sum n:Nat.a(n).P;
init sum n:Nat.a(n).P;

when this is linearised the result looks like:

proc P(s1: Pos) =
       sum e: Bool,n: Nat.
         (if(e, s1 == 2, s1 == 1)) ->
         a(n) .
         P(s1 = 1)
     + delta;

init P(2);

but it should be 

proc P =
       sum n_P: Nat.
         a(n_P) .
         P()
     + delta;

init P;

This result is also obtained by applying mcrl22lps --no-alpha.

This causes sumelm tests to fail, and it also causes tools like lpsconstelm to break.
For instance running python run.py in the directory examples/four_in_a_row now leads
to a file temp2.lps which is >50k big as lpsconstelm cannot be applied anymore, which also
means that it is virtually impossible to do any analysis on this game. 

This is a serious problem that should be resolved before the release.

**Comment by mlaveaux** [comment]
The first build in TeamCity where this test fails only contains commit 4a4cc0120948714e5e09750643289ff356459290. This commit is not part of the release branch and as such this *should* still work properly in our release candidate.

**Comment by wiegerw** [comment]
The sumelm and suminst tests are broken, since they should not rely on alphabet reduction and/or linearization. I believe the commit 4a4cc01 has nothing to do with this phenomenon.
