### ISSUE TITLE
Use fixed-width font in mcrl2ide and mcrl2xi

### ISSUE THREAD

**Issue by jkeiren** [mCRL2org/mCRL2#1555]
Currently, mcrl2ide and mcrl2xi do not use a fixed-width font in their code editors. This makes it often hard to read code that has been carefully laid out (e.g. in another editor).

In particular, in an example like the following (taken from the brp example), the first letters of the function names do not align because of the use of a variable-width font.
```
map inv: Bit -> Bit;
    indl: List(D) -> Bit;
    last: List(D) -> Bool;
    C_ind: List(D) -> Ind;
    I_ind: Bit # Bit -> Ind;
```

**Comment by Valo13** [comment]
The above commit causes the zoom functionality to behave oddly on Windows (for whatever reason). I'm afraid that an `#ifdef`'s is needed. I don't know how this has affected Linux.

**Comment by tneele** [comment]
The zoom behaviour seems fine on my Ubuntu machine.

**Comment by mlaveaux** [comment]
It might also be useful to consider `codeFont = QFontDatabase::systemFont(QFontDatabase::FixedFont);`

**Comment by Valo13** [comment]
@mlaveaux This works on Windows too
@jkeiren Could you test whether that line works on Mac as well? Even with the line `codeFont.setFixedPitch(true);` removed?

**Comment by jkeiren** [comment]
@Valo13 that works on macOS as well.

**Comment by Valo13** [comment]
Then I'll implement that as fix
