### ISSUE TITLE
pbespareqelm fails to remove some parameters

### ISSUE THREAD

**Issue by jkeiren** [mCRL2org/mCRL2#1556]
Consider the following example (taken from S.M. Orzan and T.A.C. Willemse. Invariants for Parameterised Boolean Equation Systems. In Theoretical Computer Science, 411(11-13):1338-1371, 2010.)

```
map N: Nat;
eqn N = 4;

pbes nu X(nr,nw,t,r,w: Nat) = val(r + w > 0 => r * w == 0)
  && (val(t >= 1) => X(nr + 1, nw, Int2Nat(t - 1), r + 1, w))
  && (val(nr > 0) => X(Int2Nat(nr - 1), nw, t + 1, Int2Nat(r - 1), w))
  && (val(t >= N) => X(nr, nw + 1, Int2Nat(t - N), r, w + 1))
  && (val(nw > 0) => X(nr, Int2Nat(nw - 1), t + N, r, Int2Nat(w - 1)));

init X(0,0,N,0,0);
```

For the given initial state, we can find that `nr = r` and `nw = w` are invariants.

When applying pbespareqelm to this example, this results in an output which has 4 parameters, instead of the expected three. Additionally, the debug output of the tool is not helpful in detecting the issue.

The expected output is:
```
map  N: Nat;
eqn  N  =  4;

pbes nu X(nr,nw,t: Nat) = val(nr + nw > 0 => nr * nw == 0)
   && (val(t >= 1) => X(nr + 1, nw, Int2Nat(t - 1))) 
   && (val(nr > 0) => X(Int2Nat(nr - 1), nw, t + 1)) 
   && (val(t >= N) => X(nr, nw + 1, Int2Nat(t - N)))
   && (val(nw > 0) => X(nr, Int2Nat(nw - 1), t + N));

init X(0, 0, N);
```

The actual output is
```
map N: Nat;
eqn  N  =  4;

pbes nu X(nr,nw,t,r: Nat) = val(nr + nw > 0 => nr * nw == 0)
   && (val(t >= 1) => X(nr + 1, nw, Int2Nat(t - 1), nr + 1))
   && (val(nr > 0) => X(Int2Nat(nr - 1), nw, t + 1, Int2Nat(nr - 1)))
   && (val(t >= N) => X(nr, nw + 1, Int2Nat(t - N), nr))
   && (val(nw > 0) => X(nr, Int2Nat(nw - 1), t + N, nr));

init X(0, 0, N, 0);
```

**Comment by jkeiren** [comment]
@wiegerw, the fix that I committed feels a bit quick and dirty. Therefore, I haven't closed the issue. Since this is your code, you may want to double check the fix, and think about coming up with a proper fix here.

It may also be a good idea to add an assertion at an appropriate place in the remove_parameters code that checks the input vector with indices is sorted.

**Comment by wiegerw** [comment]
Thanks for spotting this problem! Indeed remove_parameters has the requirement that the parameter indices are sorted. So perhaps it is better to use sets instead of vectors in the interface. For now I have added the requirement to the documentation of remove_parameters, and added an assertion that checks it.
