### ISSUE TITLE
IDE's message on Parsing a Property 

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1558]
Upon parsing a formula we get a message that "It is a valid formula" whereas I think it should be "It is a well-formed formula". It is explained in the attached image. 
![parsingMessage](https://user-images.githubusercontent.com/42690243/64922141-3baa2600-d7e5-11e9-8205-c1bfeedfa7da.png)

**Comment by Valo13** [comment]
Thanks for the feedback!
