### ISSUE TITLE
mCRL2-gui tool arguments wrong on Linux with KDE.

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1567]
This was an issue described by one of the students where some arguments passed to tools by mCRL2gui contained additional ampersands which our tools do not expect. I have reproduced this issue, see the following screen shot:
![issue](https://user-images.githubusercontent.com/2884328/66932121-692dfd80-f037-11e9-84e1-92786a71e142.png)

It is related to the following [1](https://bugreports.qt.io/browse/QTCREATORBUG-12680) and [2](https://bugs.kde.org/show_bug.cgi?id=337491) bug reports in the QT and KDE issue trackers respectively. The bug is caused by a program (KAcceleratorManager) in KDE that injects so-called accelerators (shortcuts for text labels typically shown by an underlined character) for some use case that the developers probably had in mind. Unfortunately, mCRL2-gui uses the (text)labels of the fields in the layout that it generates to obtain the arguments that are passed to tools and these now contain additional ampersands. 

Fixes:
 - mCRL2-gui could be changed such that the arguments are not taken from the label names, but are stored separately.
 - The bug seems to be fixed in January this year, but I don't know which KDE version contains this fix.
 - From the issue tracker: A workaround is to add the text below to `~/.config/kdeglobals` (or `kf5-config --path config` from the comment below), which prevents KDE from automatically adding accelerators. This seems to work fine as a temporary workaround.

```
[Development]
AutoCheckAccelerators=false
```

**Comment by marijnvanderhorst** [comment]
I can confirm that adding
```[Development]
AutoCheckAccelerators=false```
to the kdeglobals resolves the issue. Thanks for investigating.

Do note that on different systems, the kdeglobals file might be located in a different place. For instance, for me it is located in `~/.config/kdeglobals`. If you cannot find it, run `kf5-config --path config` to list its location.

**Comment by mlaveaux** [comment]
The configuration was indeed in ~/.config/kdeglobals and not ~/.local/, but using kf5-config is probably more robust. We have attempted to solve this issue in mCRL2-gui which should render this workaround obsolete. I will check whether this has solved the issue after our nightly have been updated. Unfortunately, the nightly builds will not update until some other issue has been solved first.

**Comment by mlaveaux** [comment]
The issue is fixed in the latest nightly release. However, note that nightly releases can be unstable and the save format of the release version is different from the nightly releases. It is probably more convenient for you to use the workaround for now.
