### ISSUE TITLE
Can we differentiating the following two formulas?

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1569]
<true*.a>true
and
<!a*.a>true

**Comment by jgroote** [comment]
Hello Muhammad,

I believe we cannot differentiate these. The first one says an action a is possible.
The second one says that an action a is possible without any preceding a's. 
If the second is true, clearly the first one is true. 
But if the first one is true, then there is a trace to a state where an a action can be done.
But in this trace there is a first a action. So, there is also a state which can be reached
without doing an a action in which an a action can be done. So, the first also implies
the second.

Hence both formulas are effectively equivalent.

Regards, Jan Friso 

> On 6 Nov 2019, at 20:58, Muhammad Atif Chattha <notifications@github.com> wrote:
> 
> <true*.a>true
> and
> <!a*.a>true
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128
