### ISSUE TITLE
Missing src directory for compiling

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1570]
The Configuration instruction given on "https://www.mcrl2.org/web/user_manual/build_instructions/configuration.html" 
assume that the sources are in <mcrl2>/src whereas the "tar" file by unzipping doesn't show any such directory.
Are there some updated instruction to compile source of mcRL2. I wanna do so on Cygwin where I have already installed the pre-requisites, like g++, make, cmake, Qt and boost. 
At the moment, I can see  the following files and directories in the available tar file for source.  

3rd-party   CMakeLists.txt        doc                          README
astylerc    COPYING               eclipse_coding_standard.xml  README.md
benchmarks  cppcheck_ignore.lst   examples                     tests
build       CTestConfig.cmake     libraries                    tools
CHANGES     CTestCustom.cmake.in  LICENSE_1_0.txt

**Comment by tneele** [comment]
These instructions just assume that you unzip (or clone when using Git) the sources in a directory called `src`. This is not related to the directory structure you see in any source tarball.

We do not have instructions specifically for Cygwin. I guess the process should not differ too much from other platforms, especially if you already installed the necessary dependencies.
