### ISSUE TITLE
mCRL2ide syntax error dependant on comment

### ISSUE THREAD

**Issue by jkeiren** [mCRL2org/mCRL2#1571]
Given the following specification:

```
proc X = delta;
     Y = delta;

init
% X ;
 Y ;
```

Checking trace equivalence between X and Y using mCRL2ide results in the following syntax error:
```
##### PARSING SPECIFICATION #####
Reading input from file '/private/var/folders/f8/gtzdyt1s26q9df0fb_2xxgrm0000gq/T/mcrl2ide-INIRWX/bug_trace_first_spec.mcrl2'...
[parser::error]   Line 6, column 1: syntax error after ';'
[parser::error]      Y ;
[parser::error]      ^
[error]   syntax error
```

The error goes away if we replace the specification by:
```
proc X = delta;
     Y = delta;

init
 X ;
% Y ;
```

The mcrl2ide project is attached as a .zip file.
[bug.zip](https://github.com/mCRL2org/mCRL2/files/3832345/bug.zip)

**Comment by Valo13** [comment]
This is an issue in mCRL2IDE caused by how the specifications for equivalence checking are created

**Comment by tneele** [comment]
There are still some related issues, I think the regular expressions still need some work. See the following screenshot.
![image](https://user-images.githubusercontent.com/3605951/69058481-0d7ad980-0a14-11ea-84de-62d0f31b4d6d.png)
The IDE says that `a` and `b` are bisimilar, even though `b` is not defined anywhere. The line with comment is significant:
```
act a;

  % ;init a;
init a.delta;
```

**Comment by Valo13** [comment]
I did not think about the situation that the init was in a comment, good find
