### ISSUE TITLE
Rewriter construction crashes with overloaded mappings and a function symbol equation.

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1576]
Consider two mappings `f,g : Nat # Nat -> Nat`. The mCRL2 toolset allows you to write an equation of the form `f = g` such that `f(5,5)` is rewritten to `g(5,5)`. However, when two additional mappings `f,g : Nat -> Nat` with a different arity are introduced such that `f` and `g` both have two overloads the initialisation of the rewriter (both jitty and jittyc) crashes. The specification below can be loaded into mcrl2xi and rewriting any expression, for example `0`, results in a segmentation fault.

``` 
map
  f : Nat # Nat -> Nat;
  f : Nat -> Nat;
  g : Nat # Nat -> Nat;
  g : Nat -> Nat;
	
eqn
  f = g;

init delta;
```

Replacing `f = g` by two equations `f(x, y) = g(x, y)` and `f(x) = g(x)` and adding variables `x,y : Nat` results in the expected behaviour. This could be corrected by suitable restrictions on the left-hand sides of equations or by adapting the code. The crash seems to occur in `get_nested_head()`.

**Comment by jgroote** [comment]
The essential problem is that the typechecker does not handle this properly. After parsing
and type checking the equation has the shape:

 DataEqn([],OpId(true,SortId(Bool),4),UntypedIdentifier(f),UntypedIdentifier(g))

This shows that the type checker was not able type check this expression. However, it
is odd that it did not report accordingly.
