### ISSUE TITLE
Data variable name clashes in mucalculus allowed by parser but not by transformation to PBES

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1580]
Given the mCRL2 specification
```
act a:Bool;
init a(true).a(false).delta;
```
and the mucalculus formula
```
exists b:Bool.<a(b)>exists b: Bool.<a(b)>true
```
executing lps2pbes results in the error `Data parameter b1 in subformula exists b1: Bool. <a(b1)>true clashes with a data parameter in an enclosing formula.`

However, when using the option --check-only which only parses and type checks the mucalculus formula, this error is not thrown. If such a name clash is not allowed in a mucalculus formula, I would expect the parser or type checker to complain about it. If we would want to allow such a mucalculus formula, the transformation to PBESs should be fixed. I imagine that this could for instance be done by first rewriting the formula to something like
```
exists b1:Bool.<a(b1)>exists b2: Bool.<a(b2)>true
```

**Comment by jgroote** [comment]
The modal formula is perfectly valid, and lps2pbes should handle it in some proper way.
What is unpleasant is that in the feedback the variable b is renamed to b1. This is confusing
and as such undesirable. I ran into this a number of times. 

It is a wrong approach to force users to uniquely name variables in binders, as it is typically
intended that with binders any name can be used. 

> On 16 Dec 2019, at 13:37, Olav Bunte <notifications@github.com> wrote:
> 
> Given the mCRL2 specification
> 
> act a:Bool;
> init a(true).a(false).delta;
> 
> and the mucalculus formula
> 
> exists b:Bool.<a(b)>exists b: Bool.<a(b)>true
> 
> executing lps2pbes results in the error Data parameter b1 in subformula exists b1: Bool. <a(b1)>true clashes with a data parameter in an enclosing formula.
> 
> However, when using the option --check-only which only parses and type checks the mucalculus formula, this error is not thrown. If such a name clash is not allowed in a mucalculus formula, I would expect the parser or type checker to complain about it. If we would want to allow such a mucalculus formula, the transformation to PBESs should be fixed. I imagine that this could for instance be done by first rewriting the formula to something like
> 
> exists b1:Bool.<a(b1)>exists b2: Bool.<a(b2)>true
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

____________________________________________________________________________________
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by Valo13** [comment]
I can no longer reproduce the issue; it can now check the formula as desired (it evaluates to true).
