### ISSUE TITLE
lts2pbes does not handle aliases.

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1583]
Consider the mcrl2 specification:

sort ID=Pos;
act a:ID;
init a(1).delta;

Applying:
mcrl22lps test.mcrl2 test.lps
lps2lts test.lps test.lts
lts2pbes -fnodeadlock.mcf test.aut -ltest.lps test.pbes -v

leads to:
Guessing output format: PBES in internal format
Detected Aldebaran extension.
Loading LPS from test.lps.
[error]   Parse error in action label a.
[error]   Parse error in action label a.
[error]   Could not find a matching action declaration for a.
[error]   type checking of multiaction failed (a)

My guess is that sort aliases are not properly dealt with.

**Comment by wiegerw** [comment]
lts2pbes only works in combination with state spaces in .lts format. A check for this needs to be added.

**Comment by jgroote** [comment]
Further investigation shows that the problem does not exist. 
lts2pbes works already fine for years on .aut and .fsm files. 

In this case the problem was in generating the file test.lts and then applying the file on a test.aut file. This can be considered as stupid.
