### ISSUE TITLE
lps2pbes does not know aliases. 

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1584]
Consider the specification test.mcrl2:
```
sort ID=Pos;
init delta;
```
and the modal formula form.mcf:
```
map f:ID->ID;
form true;
```
Applying the commands:
```
mcrl22lps test.mcrl2 test.lps
lps2pbes -fform.mcf test.lps test.pbes
```
leads to:
```
[error]   basic or defined sort ID is not declared
[error]   Type checking of data expression failed.
```
Most likely this is due to not properly applying aliases in lps2pbes when 
reading the data types in the input file. This problem may also occur in lts2pbes.

**Comment by wiegerw** [comment]
The formula specification is incomplete, because the sort ID is undefined. Note that the data specifications of the LPS and the formula specification are merged after parsing. This requires the formula specification to be self contained.

**Comment by jgroote** [comment]
I confirm that the above is the case. If possible I would like to let the datatypes
in a modal formula to be an extension of those in the specification. This makes it 
far more useful. I will change this from a bug to an enhancement.

**Comment by wiegerw** [comment]
I would prefer to solve this problem by adding include files to the mCRL2 language.

**Comment by jgroote** [comment]
The problem reported here works fine with lpsactionrename. 
The solution of lpsactionrename should be transferred to lps2pbes.

**Comment by wiegerw** [comment]
What solution are you talking about Jan Friso?

**Comment by jgroote** [comment]
There was an unlucky line data::typecheck_data_specification(result.data()) in parse_state_formula_specification which would check the data types in the modal formula file without using the data in the .lps file. However, when combining two data specifications their combination is already properly type checked. So, it turned out that the only problem was to remove this line, and lps2pbes is working again as desired.
