### ISSUE TITLE
pbessolve generates incorrect counterexample

### ISSUE THREAD

**Issue by jkeiren** [mCRL2org/mCRL2#1585]
Attached is an mCRL2 specification [spec.txt](https://github.com/mCRL2org/mCRL2/files/4058327/spec.txt) that has a state space of more than 1 state, and has deadlocks, for which pbessolve generates a counterexample that consists of a single state when checking [nodeadlock.txt](https://github.com/mCRL2org/mCRL2/files/4058326/nodeadlock.txt).

Expected: a counterexample that consists of a non-empty trace.

To reproduce, execute the following:

```
mcrl22lps spec.txt spec.lps
lps2lts -v spec.lps
lps2pbes -c -f nodeadlock.txt spec.lps spec.pbes
pbessolve -v -f spec.lps spec.pbes
lps2lts -v spec.pbes.evidence.lps
```

A preliminary investigation with @twillems and @tneele suggests the problem has to do with the way the global variable dc is dealt with. In particular, in the original LPS, parameter s_P is initialised to dc, in the counterexample it is initialised to s2, and if the LPS is generated using `mcrl22lps -f` in the LPS file it is initialised to s1.

**Comment by wiegerw** [comment]
I added debug statements for the instantation of global variables. It turns out that in one call of pbessolve different values are chosen for the global variables in the PBES and the LPS.

```$ pbessolve 1.pbes --file=1.lps --evidence-file=2.lps -d |& grep instantiating
[debug]   instantiating global PBES variables [dc:S := s1; dc2:Bool := false]
[debug]   instantiating global LPS variables [dc:S := s2; dc2:Bool := false]```

**Comment by wiegerw** [comment]
Further investigation suggests that the problem is caused by the global variable in the initial state of the LPS. I think that the summands in the generated evidence file are generated correctly, but the initial state has been instantiated with the wrong value of the global variable. If I replace s2 by s1 in the initial state, the expected trace is found.
