### ISSUE TITLE
can not run in window 10 and which window can run?

### ISSUE THREAD

**Issue by hoyeunglee** [mCRL2org/mCRL2#1587]
can not run in window 10 and which window can run?

**Comment by Valo13** [comment]
mCRL2 should run fine on Microsoft Windows 10. Could you be more specific on why you cannot get it to run on your system?

**Comment by tneele** [comment]
Since you have not responded in a while, I assume this issue has been resolved. If you have another question, feel free to reopen this issue or open another one.
