### ISSUE TITLE
mCRL2ide does not run process after two clicks

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1588]
**Steps to reproduce**:

1. Open a project in the mCRL2ide.
2. Click the button 'Simulate Specification'.
3. Close the instance of LpsXsim that opened.
4. Click the button 'Simulate Specification' again.

**Expected behaviour**: LpsXsim opens again.
**Actual behaviour**: LpsXsim does not open again. The message ```### PARSING SPECIFICATION ###``` appears in the console. The button 'Simulate Specification' can be clicked again to abort something.

The same thing occurs when clicking 'Simulate Specification' first and then 'Show State Space', or when trying to check multiple properties in succession by manually clicking on each of them. The issue does not occur when the specification is changed in the mean time or when the IDE is restarted.

**Comment by jgroote** [comment]
It seems to me that the same problem occurs with checking formulas.
Asking for a counterexample after checking leads to the response "parsing specification".

And most likely related, if you parse a formula, it immediately shows the button 
"Abort parsing", which does not disappear anymore. Pressing "Abort parsing"
changes the button in "Parse" and this can be repeated indefinitely.

It might be useful to think about a way to automatically test that such odd
behaviours are not introduced inadvertently with a next change. 




> On 28 Feb 2020, at 15:20, Thomas Neele <notifications@github.com> wrote:
> 
> Steps to reproduce:
> 
> 	• Open a project in the mCRL2ide.
> 	• Click the button 'Simulate Specification'.
> 	• Close the instance of LpsXsim that opened.
> 	• Click the button 'Simulate Specification' again.
> Expected behaviour: LpsXsim opens again.
> Actual behaviour: LpsXsim does not open again. The message ### PARSING SPECIFICATION ### appears in the console. The button 'Simulate Specification' can be clicked again to abort something.
> 
> The same thing occurs when clicking 'Simulate Specification' first and then 'Show State Space', or when trying to check multiple properties in succession by manually clicking on each of them. The issue does not occur when the specification is changed in the mean time or when the IDE is restarted.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

____________________________________________________________________________________
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by Valo13** [comment]
Fixed by commit 4fa02e969fdfc46ad84c29b115dd1e7e474b95d3
