### ISSUE TITLE
Generate trace to reach a chosen state in ltsview

### ISSUE THREAD

**Issue by yuting1012** [mCRL2org/mCRL2#1590]
The ltsview tool nicely visualizes some rare states as small spikes at the bottom of the 3D model. However, currently it is the user's job to figure out how to reach those states, which could be very difficult if the system is complex. It would be great if ltsview can automatically generate a trace that leads to a chosen state. Ideally the user can simply click on a state of interest on the 3D model, and focus on analyzing the trace(s) generated by ltsview.

**Comment by tneele** [comment]
This is actually already possible. To achieve this, active the option of viewing states (in the 'view' menu or press F3). Click a state in the LTS, it should turn brown. Then, in the simulation pane, first click 'start' and then 'backtrace'. It is now possible to step back trough the trace with the 'undo' button. We do not (yet) have a feature to automatically step forward through the trace, this you have to do manually.

**Comment by yuting1012** [comment]
> This is actually already possible. To achieve this, active the option of viewing states (in the 'view' menu or press F3). Click a state in the LTS, it should turn brown. Then, in the simulation pane, first click 'start' and then 'backtrace'. It is now possible to step back trough the trace with the 'undo' button. We do not (yet) have a feature to automatically step forward through the trace, this you have to do manually.

Thanks! Some backtraces are a little bit hard to notice in the visualization panel, but it works in general :)
