### ISSUE TITLE
Improve LaTeX export of ltsgraph

### ISSUE THREAD

**Issue by tneele** [mCRL2org/mCRL2#1591]
The LaTeX export feature of ltsgraph is experiencing some small issues, which should be addressed.

- [ ] State labels are not exported. Exporting of state labels, state numbers and edge labels should happen according to the current visibility settings.
- [ ] The colour of edge labels is not exported.
- [ ] The scale is often off. An easy fix is to introduce a '\scale' macro in the output.
- [ ] The documentclass should be 'standalone'.
- [ ] The position of labels is not exported.
- [x] When not in exploration mode, all nodes are dashed.

**Comment by FerryT** [comment]
I once refactored this class, but never merged it. Sorry for the inconvenience Thomas. Once I have access to my code base, I will reapply the restructuring I did (also to allow for the SVG exporter to work properly). Please do not worry about tidying up, apart from fixing the bugs; that's on me.

**Comment by tneele** [comment]
Ah, that sounds great. I spent some time figuring out how the LaTeX output can be improved. The ideas that I got there can of course be applied after you merge your changes.

**Comment by FerryT** [comment]
The refactor has been applied along with the SVG exporter. In think we still mis some of the bullet points though.

**Comment by tneele** [comment]
@FerryT thanks for reminding me. I resolved most of the remaining issues, although in the end I chose not to implement node positioning. LaTeX's standard positioning is relatively good, and it is hard to reproduce exactly what is shown in LTSgraph itself, since the font size may be off.
