### ISSUE TITLE
Odd message of lts2pbes

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1592]
Given the specification (test.mcrl2)

```
act a;
init a.delta;
```

and the formula (`form.mcf`)
```
form <a>true;
```

When applying the commands:

```
mcrl22lps test.mcrl2 test.lps
lps2lts test.lps test.lts
lts2pbes test.lts -f form.mcf test.pbes
```

We get the message:
```
Warning: the modal formula contains an action a that does not appear in the LPS!
```

This is very confusing, and not correct as a is properly defined, and actually occurs in the state space.

I believe this message is very useful when correct. But in this case it is incorrect to print it, and it actually caused us quite some time when investigating what we did do wrong when looking at a car safety specification at NXP.

**Comment by wiegerw** [comment]
I cannot reproduce the issue. What version of mCRL2 did you use?

**Comment by yuting1012** [comment]
> I cannot reproduce the issue. What version of mCRL2 did you use?

I use version 201908.0-1ubuntu1ppa2~bionic and had the same issue

**Comment by jgroote** [comment]
Sorry, I mistyped the formula. It should be:

form <a>true;

I just checked it with the latest version of the toolset, and the problem is there too. 
This latest version is:

[Werkkamer:~/test] jfg% lts2pbes --version
lts2pbes mCRL2 toolset 201908.0.04c9edbb69M (Release)

**Comment by jgroote** [comment]
Oh, I see what the problem is. 

The formula is diamond a true. 
If you type that in here the  smaller_bracket a larger_bracket are removed form the text for whatever reason.

**Comment by tneele** [comment]
@jgroote Github uses Markdown for formatting comments. The `<` and `>` are part of its syntax. I updated your comments with formatting for verbatim text.

I can reproduce the issue.
