### ISSUE TITLE
Removal of [true*] from a formula 

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1593]
Can someone comment upon removal of [true*] from the following formula?
[true*](forall p: Phil. mu Y. ([!eat(p)]Y && <true>true))

**Comment by jgroote** [comment]
Dear Muhammad,

In the formula:

> [true*](forall p: Phil. mu Y. ([!eat(p)]Y && true))

you may want to replace the last true with <true>true.

With the [true*] in front it means in every state each philosopher p will perform an eat(p) action within a finite number of steps.
Without the [true*] it means in the initial state each philosopher p will perform an eat(p) action within in finite number of steps.

Assume that there is one philosopher Socrates, then the formula with [true*] in front is invalid for the following
process, while the one without [true*] is valid.

proc X=sleep(Socrates).X;
init eat(Socrates). X;

I hope this is informative.
Regards, Jan Friso 

> On 24 Apr 2020, at 21:53, Muhammad Atif Chattha <notifications@github.com> wrote:
> 
> 
> Can someone comment upon removal of [true*] from the following formula?
> [true*](forall p: Phil. mu Y. ([!eat(p)]Y && true))
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128
