### ISSUE TITLE
Quatifiers and sets with a regular formula

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1598]
Suppose an action `transferSet:Set(Int)`.

I am trying to express that there exits an action `transferSet` that contains at least one negative value in its set.
```
exists i:Int.exists s:Set(Int).<true*.transferSet(s)>true && i<0 && i in s 
```
This is a syntax error due to `i<0 && i in s`. I need advice to remove this error.

Secondly, I tried to find existence of the action `transferSet` with an arbitrary set
```
exists s:Set(Int).<true*.transferSet(s)>true
```
There's no syntax error but evaluation process stops immediately by giving
```
##### SOLVING PBES #####
Generating parity game...

[error]   Unexpected term exists s1: Set(Int). Y(1, 1, {}, s1) encountered in Rplus
```

**Comment by tneele** [comment]
To write a data expression in a mu-calculus formula, you need to use the `val` keyword, as follows:
```
exists i:Int.exists s:Set(Int).<true*.transferSet(s)>true && val(i<0 && i in s)
```
I'm not familiar with the second error, but I guess it is related to the fact that sets cannot be enumerated. A solution is probably to change the nesting of the quantifiers, like this:
```
<true*> exists s:Set(Int). <transferSet(s)>true
```
Nesting the quantifier in this way also helps to reduce the size of the underlying parity game. Let me know if this resolves the problem.

**Comment by matifch** [comment]
Thanks Thomas! 
With the keyword "val", the syntax problem is solved. So kind of you. 
 I tried the following formula which is showing almost the same error as the second error reported in this thread. 
[true*]exists s:Set(Int).mu X.[!transferSet(s)]X  && <true> true && exists i:Int.val(i<0 && i in s)

for the specification:

act  
 transferSet:Set(Int);
init 
transferSet({1,2}).delta;

Error is:
##### SOLVING PBES #####
Generating parity game...

[error]   Unexpected term exists s2: Set(Int). X0(2, s2) encountered in Rplus

**Comment by tneele** [comment]
For this formula, there is no equivalent formula that can be checked by the tools. The reason is that the nesting of `exists s:Set` with respect to `mu X. [!transferSet(s)]X` cannot be changed without altering the semantics of the formula. A reasonable alternative is perhaps
```
[true*] (mu X. [!(exists s:Set(Int), i:Int. val(i < 0 && i in s) && transferSet(s))] X && <true> true)
```
When using this kind of structure, pay attention to using `<true>true`, and not `true`.
