### ISSUE TITLE
Communication, right hand side action allowed in left hand side

### ISSUE THREAD

**Issue by FerryT** [mCRL2org/mCRL2#1607]
The book states:
> (...) a right hand side of a communication cannot occur in a left hand side. Otherwise,
γC1(γC2(α)) = γC2(γC1(α)) would not necessarily hold. Hence, γC1∪C2(α) is not uniquely defined and γC would not be a properly defined function.

However the following is allowed: (note in particular the `c` action)
```mcrl2
act a, b, c, d, e, f;

proc X = a.c.X;
proc Y = b.d.Y;
proc Z = d.Z;

init comm({a|b -> c, c|d -> e}, X || Y || Z);
```

**Comment by tneele** [comment]
The conclusion from our discussion today is that the issue is a bit more involved. Communication rules such as `a | a -> a` are quite common in existing models, and should not lead to an error for reasons of backwards compatibility. In other cases, the restrictions of the book should be followed.

**Comment by jgroote** [comment]
The last commit resolved this issue.
