### ISSUE TITLE
State information is missing in .fsm files. 

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1608]
For unclear reasons state information is missing in .fsm files. This is a serious problem. 

```
mcrl22lps abp.mcrl2 abp.lps 
lps2lts abp.lps abp.fsm 
```

gives a file that starts with 

```
0 0 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 0 0
1 1 0 0 0 0 0 0 0 0
2 0 1 0 1 0 0 0 0 0
2 1 1 1 1 0 0 0 0 0
```

**Comment by wiegerw** [comment]
Since the class `lts_fsm_builder` inherits all functionality from `lts_lts_builder`, I guess that the problem is inside the routine `lts_convert`.
