### ISSUE TITLE
Difference between a(0) and a(j-j)

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1610]
The following example is a candidate for lpssumelm but by changing the process `P1` as `P1(j:Nat) = a(j-j).delta;`, it doesn't.  In other words `a(0)` action is treated differently from `a(j-j)`. Can we add a tool lps**expression**elm or can simplify an expression to obtain some optimization?

```
act a:Int; b;
proc
  P = sum i:Nat.b.P1(i+1);
  P1(j:Nat) = a(0).delta;
init
  P;
```

**Comment by tneele** [comment]
There is the tool lpsrewr that can simplify expressions by applying the (standard) rewrite rules from the data specification. In this case, the expression `j - j` cannot be rewritten further than `@monus(j, j)`. We could decide to add a rewrite rule

```
@monus(n, n) = @c0
```

@jgroote What is your opinion on this matter?

**Comment by jgroote** [comment]
There is always a trade off between adding an extra rewrite rule, 
and having a faster rewriter. But this is a natural rule, and we could
decide to add it. I do not have a very strong opinion in this matter.

If you and Muhammad have such an opinion you could add it. 
Jan Friso 

> On 10 Jul 2020, at 14:09, Thomas Neele <notifications@github.com> wrote:
> 
> 
> There is the tool lpsrewr that can simplify expressions by applying the (standard) rewrite rules from the data specification. In this case, the expression j - j cannot be rewritten further than @monus(j, j). We could decide to add a rewrite rule
> 
> @monus(n, n) = @c0
> 
> @jgroote What is your opinion on this matter?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by matifch** [comment]
I think Thomas Neele is in a better position to decide this trade off.
