### ISSUE TITLE
Obtaining tau confluent state space

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1611]
I was trying to get a state space to obtain results of lpsconfcheck from the following specification.

```
act a,b;
proc
 P0 = a.delta;
 P1 = b.delta;
init
 allow({a,b},
  hide({b},
   P0||P1));
```

But I get three transition from the initial state while I expect two and  the resultant LPS is not tau confluent. By removing the hide operator I get two transitions from the initial state. I am using nightly build version 202006.0.6982d7dc57.  By the way the release version is not available for download at the moment.

**Comment by tneele** [comment]
To obtain the desired result, you have to change the order of the hide and allow operators, like so:
```
act a,b;
init hide({b}, allow({a,b}, a.delta || b.delta));
```
This results in an LPS with one confluent tau summand.

We are working on making the latest release available. The previous release is still available for download via https://github.com/mCRL2org/mCRL2/releases/tag/mcrl2-201908.0.

**Comment by matifch** [comment]
Thanks @tneele 
I am surprised to see the following specification is tau-confluent 
act a,b;
init hide({b}, allow({a,b}, a.delta || b.delta));

but not the following one:

act a,b;
init 
(a.tau+tau.a).delta;

**Comment by tneele** [comment]
The tau summand in the latter specification _is_ confluent, but that is not detected by lpsconfcheck, which computes an under-approximation of confluent tau summands. The detection algorithm in lpsconfcheck is mostly geared towards detecting confluence that emanates from parallel processes and not from 'coincidental' confluence as in your second specification.

The confluence in the second specification can be found by the experimental tool pbespor, which executes a partial-order reduction algorithm on PBESs.
