### ISSUE TITLE
Configuration mCRL2 over Ubuntu

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1615]
Can anyone guide in configuring mCRL2 on Ubuntu. Screenshot after following the installation steps is attached below. 
Moreover, the output of grep of installed ppa is also here but I am unable to find the installation folder for mCRL2 being new to Ubuntu. 

```
$ grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/*
/etc/apt/sources.list.d/mcrl2-ubuntu-release-ppa-focal.list:deb http://ppa.launchpad.net/mcrl2/release-ppa/ubuntu focal main
/etc/apt/sources.list.d/mcrl2-ubuntu-release-ppa-focal.list:# deb-src http://ppa.launchpad.net/mcrl2/release-ppa/ubuntu focal main
/etc/apt/sources.list.d/mcrl2-ubuntu-release-ppa-focal.list.save:deb http://ppa.launchpad.net/mcrl2/release-ppa/ubuntu focal main
/etc/apt/sources.list.d/mcrl2-ubuntu-release-ppa-focal.list.save:# deb-src http://ppa.launchpad.net/mcrl2/release-ppa/ubuntu focal main
```
![Screenshot from 2020-07-25 14-00-06](https://user-images.githubusercontent.com/42690243/88453477-a3f37a80-ce80-11ea-80b4-aac1bf4f2c55.png)

**Comment by tneele** [comment]
Your question is a bit unclear, what is exactly the problem?

Perhaps the following can already help your troubleshooting:

- Did you actually install mcrl2? This has to be done by running the command `sudo apt-get update && sudo apt-get install mcrl2`.
- Checking whether it is installed can be done with `dpkg -l mcrl2`.
- If it is installed, the files that are part of the package can be listed with `dpkg -L mcrl2`.

**Comment by matifch** [comment]
Thanks @tneele, I was not using the command to install mCRL2. It is working fine now.
