### ISSUE TITLE
mcrl2ide does not allow pasting in the name of a modal formula

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1621]
Pasting in the name field of a modal property does not appear to be possible in mcrl2ide.
This was observed on a mac.

**Comment by Valo13** [comment]
I cannot reproduce this on Windows.
Both pasting via Ctrl + v and via the context menu (when you right click) work fine for me.

**Comment by Valo13** [comment]
The name field for a property only allows alphanumeric characters, underscores and spaces. Did you try to paste something that contains a character that is not allowed in this field? When I try to paste something with a disallowed character I can reproduce that nothing is pasted in the property name field.

**Comment by jgroote** [comment]
Ik did not know that this was the problem. 
I may have substituted a dot, beeing part of the name of a
modal formula. 

Maybe we should then close this, although others may be
confused by this behaviour also, but I don't think that a
non standard solution for this should be implemented.



> On 26 Aug 2020, at 10:41, Olav Bunte <notifications@github.com> wrote:
> 
> 
> The name field for a property only allows alphanumeric characters, underscores and spaces. Did you try to paste something that contains a character that is not allowed in this field? When I try to paste something with a disallowed character I can reproduce that nothing is pasted in the property name field.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven. 
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
J.F.Groote@tue.nl, www.win.tue.nl/~jfg, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128

**Comment by Valo13** [comment]
I'll see some time if I can add feedback to the property name field in such cases. I'll put it on the mCRL2IDE TODO list.
