### ISSUE TITLE
The 202006.0 release does not work under macOS 10.13.6

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1622]
I installed the release version on macOS and upon starting IDE or GUI I am getting the following message on terminal where the terminal is automatically opened. 
```
/Applications/mCRL2.app/Contents/bin/mcrl2ide ; exit;
Muhammads-MacBook-Air:~ muhammadatif$ /Applications/mCRL2.app/Contents/bin/mcrl2ide ; exit;
qt.qpa.fonts: Populating font family aliases took 822 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 
```

Moreover while parsing a specification I get,

```
##### PARSING SPECIFICATION #####
Reading input from file '/Users/muhammadatif/Documents/frogs/frogs_spec.mcrl2'...
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/mCRL2.app/Contents/bin/../lib/libmcrl2_data.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/mCRL2.app/Contents/bin/../lib/libmcrl2_data.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

The given specification is not a valid mCRL2 specification
```

**Comment by tneele** [comment]
To debug this effectively, it would be nice if you could provide some more details. Are you referring to the latest mCRL2 release 202006.0? Which version of macOS are you using? Do you see the dyld error only in the IDE or also when using tools via the command line?

**Comment by matifch** [comment]
Thanks Thomas!
Here are answers of your questions.

> To debug this effectively, it would be nice if you could provide some more details. 
>Are you referring to the latest mCRL2 release 202006.0? 
Yes. 
>Which version of macOS are you using? 
macOS 10.13.6 (17G14019)
>Do you see the dyld error only in the IDE or also when using tools via the command line?
Also on command line.

**Comment by tneele** [comment]
It seems like the release build we created under macOS 10.15 is not compatible with 10.13.6. I suggest you upgrade your OS or compile the toolset from source yourself. Is that a workable solution for you?

**Comment by matifch** [comment]
Sure, I can try by upgrading OS. For compilation, is there any guidance available? I am asking being new to macOS. 
Please change the title of this thread as the problem in not specific to IDE/GUI.

**Comment by tneele** [comment]
To be honest, our build instructions are slightly outdated, but it's not very complicated. First, you need to install Qt, CMake and Boost (instructions can be found on the internet). Then, you can run the following commands to build mCRL2:
```
git clone https://github.com/mCRL2org/mCRL2 src
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ../src
make -j4
```
If CMake throws an error about not being able to find Boost or Qt, you can set these paths manually with `ccmake`.
