### ISSUE TITLE
Ltsconvert ignores --tau option in case of unreachable transitions

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1627]
We start with the following LTS (test.aut):
```
des (0,2,3)
(0,"a",1)
(2,"a",1)
```
Then applying ltsconvert with the command `ltsconvert test.aut test2.aut --tau=a` yields the following LTS in which the unreachable transition has been removed:
```
des (0,1,2)
(0,"a",1)
```
Applying ltsconvert again using the command `ltsconvert test2.aut test3.aut --tau=a` yields the following LTS in which the `a`-actions have been replaced by `tau`-actions:
```
des (0,1,2)
(0,"tau",1)
```

I would expect that only one run of ltsconvert is needed to get from test1.aut to test3.aut.
When additionally using the option `--no-reach`, the `a`-actions are replaced by `tau` actions in one go (but of course the unreachable transition remains).

**Comment by jgroote** [comment]
Resolved in commit 8842e0c5f..858c0797b.
