### ISSUE TITLE
Faulty counterexample for mucalculus formula with quantifiers with same declared variable names

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1628]
This is based on a student project for system validation.

Consider [this mCRL2 project](https://github.com/mCRL2org/mCRL2/files/5430025/Waterlock.zip).
It contains an mCRL2 specification of a water lock and three mucalculus formulae that all aim to model the same property: the waterlock may only open whenever the water levels on both sides of the lock are the same.
There are only minor differences between the formulae, regarding the universal quantifiers:
 - 3a with brackets: has brackets around the universal quantifiers to enforce the scope that the quantifiers should be defined over.
 - 3a without brackets: does not have the above mentioned brackets, which increases the scopes of the universal quantifiers since `&&` binds stronger.
 - 3a without brackets renamed: same as above except that the variables declared in the universal quantifiers are renamed such that there are no name clashes.

One would expect that all three formulae have the same semantics. The first and third have, but the second yields different results. They all evaluate to false, but the counter example of the second formula is different. The counterexamples of the first and third formulae contain an action (`water_level(inside, 1)`) that changes the water level on one side just before the doors are opened, which correctly shows that the water levels on both sides can be different when the doors open. The counterexample of the second formula does not contain this action, which makes this a bad counterexample because when the doors are opened both water levels are the same.

The fault seems to be in the use of declared variables in nested quantifiers with the same name (`l''`). I think the following may be the case: When dealing with the outer quantifier, it seems to consider any `l''` within the scope of this quantifier, even when some occurrences of `l''` are references to the declarations of the inner quantifier.
Another interesting observation is that computing the value and the counterexample for the second formula takes considerably more time compared to the other formulae.

I tried to make a smaller example but I did not manage to make it work. I am also not sure whether this issue can make the difference between a formula being true or false.

Generated counterexample LTSs can be found in the artefacts folder.

**Comment by twillems** [comment]
This is not so much a bug in the counterexample generation as it is a bug in the conversion from LPS to PBES, see issue #1629.

All three formulae give the same counterexample when replacing the following line in the second formula:

`!(exists s:Side. exists l'':Nat. water_level(s,l''))`

by

`!(exists s:Side. exists k'':Nat. water_level(s,k''))`.

**Comment by Valo13** [comment]
Solving issue #1629 has solved this issue as well (all counterexamples are now the same)
