### ISSUE TITLE
Result pbes2bool and pbessymbolicbisim differs

### ISSUE THREAD

**Issue by bobismijnnaam** [mCRL2org/mCRL2#1633]
I have the following two files

infcoffee.mcrl2

```mcrl2
sort Coin = struct nickel | dime;

act order, coffee; insert : Coin;

map value: Coin -> Nat;

eqn	value(nickel) = 5;
	value(dime) = 10;

proc 
	Machine(idle: Bool, balance: Nat) =
			(idle -> order . Machine(false, balance))
		+
			(sum c: Coin . (!idle) -> insert(c) . Machine(false, balance + value(c)))
		+
			(((!idle) && (balance >= 15)) -> coffee . Machine(true, 0));

init Machine(false, 0);
```

infcoffee_eventually.mcf

```mcrl2
< true* . order > true
```

When checked with `pbes2bool` and `pbessymbolicbisim`, the results differ:

```bash
$ mcrl22lps infcoffee.mcrl2 | lps2pbes -f infcoffee_eventually.mcf | pbes2bool
true
$ mcrl22lps infcoffee.mcrl2 | lps2pbes -f infcoffee_eventually.mcf | pbessymbolicbisim
Partition refinement completed in 0.0240541 seconds.
false
```

I would expect them to both to be true. Is there a side condition/requirement that's not satisifed for pbessymbolicbisim for this mcrl2 program? I would expect it to have some constraints but I have not been able to find a list. I'm using mcrl2 version 202006.

**Comment by twillems** [comment]
Running pbessymbolicbisim with flag '-d' reports a segfault on my machine, indicating something's fishy.
@tneele can probably better tell what's going on and solve it.

I observe, however, that in this case, eliminating the (existential) quantifier in the PBES leads to the correct solution without segfaulting:

`$ mcrl22lps infcoffee.mcrl2 | lps2pbes -f infcoffee_eventually.mcf | pbesrewr -pquantifier-finite | pbessymbolicbisim`
`true`
