### ISSUE TITLE
LpsXSim, no horizontal scrolling "State Change"

### ISSUE THREAD

**Issue by astramaglia** [mCRL2org/mCRL2#1637]
I have been trying to use LpsXSim (from the last version of mCRL2) but I found it hard to use because I was not able to see all the 'parameter := value' related to the actions in the section 'State Change' (even with the expansion of this section to the full screen). Without these information, if you try to replicate a trace, it is really hard to deal with the tool, because you are not able to see all the information needed for the action to take. 
(A way that I found to solve my problem is to use lpssim considering the parameters displayed by LpsXSim to understand which value is related to which parameter in the lpssim command line)

**Comment by Valo13** [comment]
Yeah I have experienced this too. What I did to work around this was to select the cell and then use ctrl+c to copy the contents, but that's not really a great option too. Would a horizontal scroll bar (per cell when necessary) suffice? I could look into adding this when I have time, I don't expect it to be much work.

**Comment by astramaglia** [comment]
I think a scroll bar upper-left window would be enough, or maybe just in the side of the 'State Change' :). 
Just to be able to see all the parameters and respective values.
![image](https://user-images.githubusercontent.com/78547823/106908561-b25c0200-66ff-11eb-9736-59383ced039e.png)

**Comment by tneele** [comment]
Actually, it was already possible to resize the 'state change' column manually, by hovering over and then dragging its right edge. This wasn't very intuitive though, and the behaviour of the scrollbar was also a disaster. Commit ba9788caf24 should improve this a bit. The rightmost column in all of the three tables is now automatically resized to fit its contents. Is this sufficient?

**Comment by jgroote** [comment]
I tried this and it now seems easy to use the mouse to move the state to left and
right. I did not observe this behaviour before, but this looks elegant.
I am not sure whether this is recent or old behaviour, but it appears sufficient to me
for the moment.

------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven.
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
***@***.******@***.***>, www.win.tue.nl/~jfg<http://www.win.tue.nl/~jfg>, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128


From: Thomas Neele ***@***.***>
Date: Friday, 2 April 2021 at 20:59
To: mCRL2org/mCRL2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [mCRL2org/mCRL2] LpsXSim, no horizontal scrolling "State Change" (#1637)

Actually, it was already possible to resize the 'state change' column manually, by hovering over and then dragging its right edge. This wasn't very intuitive though, and the behaviour of the scrollbar was also a disaster. Commit ba9788c<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FmCRL2org%2FmCRL2%2Fcommit%2Fba9788caf248f4e518a4867211f99bb80258c448&data=04%7C01%7C%7Ca6337a477dab46ae82ac08d8f609705c%7Ccc7df24760ce4a0f9d75704cf60efc64%7C1%7C0%7C637529867684209094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=176VIFyqcT2KNj3CtGNJIAZJMkF%2BHxUZUjks%2BIs7cvk%3D&reserved=0> should improve this a bit. The rightmost column in all of the three tables is now automatically resized to fit its contents. Is this sufficient?
