### ISSUE TITLE
ltsgraph on Windows 10 and Unsupported OpenGL version

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1639]
Please see the attached image to know the bug closely where an error message appears upon starting ltsgraph. I have tried to update the driver but the manufacturer (i.e., Intel) is saying , "No supported driver or software updates are available for your system". I am using  mCRL2 toolset 202006.0.6e870d5fe9 (Release). 
![openGL](https://user-images.githubusercontent.com/42690243/111585401-7d21e580-877c-11eb-9ac1-7496015bfde1.png)

**Comment by tneele** [comment]
After some searching, it looks like Intel has not updated the Windows driver for their 'HD graphics 2000' embedded GPU (which is what your CPU has) with support for OpenGL 3.3. See https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html.

There are several options:
- If your laptop also contains a discrete GPU from AMD or NVIDIA, it might be able to run OpenGL 3.3 on that hardware.
- According to [this thread](https://www.reddit.com/r/intel/comments/iob8nz/intel_hd_graphics_2000_driver_opengl_33_support/) on Reddit, the Mesa driver for Linux *does* have support for OpenGL 3.3. Thus, ltsgraph may run fine on this laptop under Linux.
- Export your graph to the AUT format and load it in ltsgraph from the 201808.0 release. This version of ltsgraph still runs on lower OpenGL versions.
