### ISSUE TITLE
pbessolve segfaults when providing incorrect file used for generating PBES

### ISSUE THREAD

**Issue by jkeiren** [mCRL2org/mCRL2#1640]
When solving a pbes that was generated with counterexample information, and asking for a counterexample, `pbessolve` segfaults if the wrong file is provided. This suggests we should do proper error checking when generating counterexample information.

### To reproduce

1. Download and unpack the attached [bug.zip](https://github.com/mCRL2org/mCRL2/files/6169294/bug.zip)
2. Generate a PBES using the following commands:

```
mcrl22lps bug.mcrl2 bug.lps
lps2lts bug.lps bug.lts
lts2pbes -c -l bug.lps -f nodeadlock.mcf bug.lts bug.pbes
```

3. Solve the pbes using `pbessolve -f bug.lps bug.pbes`. Note that here is use `bug.lps`, whereas I should have used `bug.lts`

This last command segfaults during the extraction of the structure graph. The last couple of lines of the debug output are as follows:

```
[debug]     --- solution for solve_recursive input ---
[debug]      0 vertex(formula = Y'0, decoration = conjunction, rank = 0, predecessors = [ 11 ], successors = [ 1 ], strategy = undefined)
[debug]      1 vertex(formula = Y'1 && Zpos_0_a(0, 1) || Zneg_0_a(0, 1), decoration = disjunction, rank = undefined, predecessors = [ 0 ], successors = [ 2 ], strategy = 2)
[debug]      2 vertex(formula = Y'1 && Zpos_0_a(0, 1), decoration = conjunction, rank = undefined, predecessors = [ 1 ], successors = [ 4 ], strategy = 4)
[debug]      4 vertex(formula = Y'1, decoration = conjunction, rank = 0, predecessors = [ 2 ], successors = [ 10 ], strategy = undefined)
[debug]     10 vertex(formula = Y'0 && Zpos_2_b(1, 0) || Zneg_2_b(1, 0), decoration = disjunction, rank = undefined, predecessors = [ 4 ], successors = [ 11 ], strategy = 11)
[debug]     11 vertex(formula = Y'0 && Zpos_2_b(1, 0), decoration = conjunction, rank = undefined, predecessors = [ 10 ], successors = [ 0 ], strategy = 0)
[debug]      W0 = { 0, 4, 11, 2, 10, 1 }
[debug]      W1 = {  }
[verbose] Extracting evidence...
[debug]   Extracted minimal structure graph { 0, 1, 2, 3, 4, 6, 7, 8, 10, 11, 12 }
[1]    38414 segmentation fault  pbessolve -d -f bug.lps bug.pbes
```
 
### Expected behavior

The tool throws an error message indicating some information cannot be found. If possible with a hint that the user may have used the wrong argument to the `-f` flag, and exits gracefully.

**Comment by tneele** [comment]
In your list of commands, you use `lps2pbes`, but the options you supply suggest to me that you meant to write `lts2pbes`, is that correct?

**Comment by tneele** [comment]
After looking into this a bit, I don't think it can be resolved completely without changing the PBES format to include more information about the LPS/LTS it was created from. Right now, the extra PBES variables just contain some indices that are used to extract the right transitions from the LPS/LTS. For your example, this causes an index out of bounds problem, since the LTS has more transitions that the LPS has summands. The other way around is also possible, by the way.

The easiest solution I see is to just throw an exception if this occurs during the construction of the counter-example. A more rigorous option is to check beforehand whether the maximum index that occurs in the PBES does not exceed the number of summands/transitions in the LPS/LTS. If someone has a strong opinion for or against either solution, let me know.

**Comment by jkeiren** [comment]
> In your list of commands, you use `lps2pbes`, but the options you supply suggest to me that you meant to write `lts2pbes`, is that correct?

Indeed, I meant to say `lts2pbes`. I updated the report.

**Comment by jkeiren** [comment]
> The easiest solution I see is to just throw an exception if this occurs during the construction of the counter-example. A more rigorous option is to check beforehand whether the maximum index that occurs in the PBES does not exceed the number of summands/transitions in the LPS/LTS. If someone has a strong opinion for or against either solution, let me know.

I think it would be fair to throw an exception at the point where the index out of bound would appear. Especially, I think it would be nice if this gives a hint as to where the problem is.

**Comment by jgroote** [comment]
The best solution might be to store some extra information in the pbes about the lps from which it came. Maybe in 
extremo store the complete lps in the pbes, which I would consider most elegant. 
Probably, for the time being throwing an exception might be the fast solution.

**Comment by tneele** [comment]
Storing the complete LPS/LTS inside the PBES is convenient, but does have the drawback that the PBES may double in size (or worse), if it is generated from a very large LTS.

1f86fde6c94 should fix this issue.

**Comment by wiegerw** [comment]
The solution provided by Thomas seems adequate to me. I would not store an LPS or LTS inside a PBES.
