### ISSUE TITLE
Renaming properties crashed the IDE

### ISSUE THREAD

**Issue by OmerSakar** [mCRL2org/mCRL2#1641]
I renamed a property named "InitEventuallyWishZero" to "InitEventuallyWishZeroCrash" and the IDE crashed.
 
The minimal steps to reproduce this issue are:
- Create project
- Create a property
- Rename property

This issue has been reproduced with:
- mCRL2 version 202006.0 (Release) on macOS Catalina 10.15.7
- mCRL2 version 202006.0 (Release) on macOS Big Sur 11.2.3

**Comment by Valo13** [comment]
At what point does it crash? When you try to change the name in the name field or when you press a button after changing a name? If you run it from command line, does it mention any errors there when it crashes?

**Comment by OmerSakar** [comment]
That is a good idea. So the (more precise) steps are:

- Started mcrl2ide from the command line
- Created a project with the button in the top left corner
- Created a property with the second-to-last button from the right (in the top bar)
- Saved that property
- Clicked on the edit button for that property
- Filled in new name
- Clicked save button
- Crash resulting in the following

```
omer@funnynamehere bin % ./mcrl2ide 
qt.qpa.fonts: Populating font family aliases took 386 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

zsh: segmentation fault  ./mcrl2ide
omer@funnynamehere bin % 
```

**Comment by Valo13** [comment]
Hmm, it seems that there is no monospace font defined in your MacOS, but I'm not sure that that has to do with the crash. If you type something in the editor, does it show up in a monospace font?

**Comment by jgroote** [comment]
To me it appears monospace. A space and a capital double u (W) take up an equal amount of space.

**Comment by OmerSakar** [comment]
> Hmm, it seems that there is no monospace font defined in your MacOS, but I'm not sure that that has to do with the crash. If you type something in the editor, does it show up in a monospace font?

Yes, it seems to be monospace in the editor.

**Comment by jgroote** [comment]
Some testing (with Ferry) on a mac leads to the following observations:
1) On a mac it is impossible to change letters in the property name from capital to a small letter or vice versa. It will say that the property already exists.
2) Changing the execution permissions on the directory "properties" leads to an instant crash of mcrl2ide. The thrown exception should  be caught when writing or renaming the file.

**Comment by Valo13** [comment]
1: I found that checking whether a propertyname already exists is done by first changing them to lowercase. I'm pretty sure I did this because Windows (the OS I use) does not differentiate between capital and lowercase letters for file names. I see now that this goes wrong for other OSs.
2: You shouldn't make manual changes to the project folders and files in the first place, but I see that having some general exception catching would make it easier to find bugs.

**Comment by jkeiren** [comment]
I can reproduce this issue with the release

```
mcrl2ide --version
mCRL2ide mCRL2 toolset 202006.0 (Release)
```

However, with the current master, I cannot reproduce the issue anymore.

Tested using d47bcef976

```
mcrl2ide --version
mCRL2ide mCRL2 toolset 202006.0.d47bcef976M (Release)
```

**Comment by Valo13** [comment]
Hmm, that's interesting. Since the last release the add/edit property dialog has been overhauled somewhat and it looks like this has coincidentally fixed this issue. @OmerSakar Could you confirm that it does work on the nightly build?

**Comment by mlaveaux** [comment]
Closed due to inactivity and the fact that we can no longer reproduce this issue. If it still occurs then the issue can be reopened.
