### ISSUE TITLE
Lts library calculates wrong number of states for probabilistic transition systems.

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1643]
The number of states in  probabilistic lts is wrong after loading the lts.
Below a part of the results of the state space generation of shared_coin_protocol.mcrl2 (see examples/probabilistic).
The results are correct for .aut files.  It also goes wrong for:

act a:Bool;
    proc X=dist b:Bool[1/2].a(b).X;
    init X;

Command:

mcrl22lps shared_coin_protocol.mcrl2 shared_coin_protocol.lps
lps2lts --verbose shared_coin_protocol.lps shared_coin_protocol.lts
ltsinfo shared_coin_protocol.lts 

Relevant part of the output:

Loading LPS from shared_coin_protocol.lps.
Replacing global variables with dummy values.
165282st, 330268tr, explored 99.91%. Last level: 366, 70st, 140tr. 
done with state space generation (433 levels, 170408 states and 340816 transitions)
Starting to save a probabilistic lts to the file shared_coin_protocol.lts.
[werkkamer:~/test] jfg% ltsinfo shared_coin_protocol.lts 
Number of states: 340816.
Number of action labels: 9 (including a tau label).
Number of transitions: 340816.
Number of state labels: 340816.
Warning: some states are not reachable from the initial state! (This might result in unspecified behaviour of LTS tools.)
LTS is not deterministic.
This lts has 340817 probabilistic states.
Out of these 43178 contain a non trivial probability distribution.
The initial state is not probabilistic.

**Comment by mlaveaux** [comment]
It was only my intention to refer to this issue in the commit message. I will leave this issue open until some further testing with probabilistic lts files has been performed.

**Comment by jgroote** [comment]
Does this mean that you do not see that there is a problem? I guess it is due to the redesign of the .lts format to streams, but I am not sure.

**Comment by mlaveaux** [comment]
No, commit (e4d838e) should resolve this problem. The problem was that the probabilistic states would not obtain a unique index while loading, because the add_probabilistic_state function does not account for duplicates. Instead we have to give probabilistic states a unique index by using an indexed_set. The .lts format did not have to change to solve it, but the problem was indeed introduced when the .lts format was redesigned to streams.

**Comment by jgroote** [comment]
This problem now appears to be fixed.
