### ISSUE TITLE
lps2pbes mixes up bound variables in fixed point that have the same name. 

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1644]
In formulas where the same fixed point variable is used multiple times, the bound variables
are not bound to the correct variable. The example below shows this. 

Formula: form.mcf
nu X.mu Y. ([a]X&&[!(b||a)]Y && <true>true)
&&
nu X.mu Y. ([b]X&&[!(a||b)]Y && <true>true)
 
Specification test.mcrl2. Its content is not really relevant. 
act a,b;
proc X= a. X+b.Y;
     Y= b.delta;
init X;
 
Command:
mcrl22lps test.mcrl2 test.lps ; lps2pbes test.lps -fform.mcf -d test.pbes
 
Using -d in lps2pbes the parsed formula is printed. It is shown below. Note that the first X and Y
are renamed to Z and X0. Both bound occurrences of X and Y are bound renamed to Z and X0 whereas
the last ones shoud become Y0 and Z0. Note that Y0 and Z0 are only declared in a fixed point 
but not used. 
 
[debug]   formula after preprocessing:  nu Z. mu X0. [a]Z && [!(b || a)]X0 && <true>true && (nu Y0. mu Z0. [b]Z && [!(a || b)]X0 && <true>true)

**Comment by twillems** [comment]
The problem appears to be with fixed point variables that have already been bound in the larger scope, as the following example suggests:

`nu X. mu X. X` 

this formula is logically equivalent to false (e.g., the process `init delta;` does not satisfy this formula)

lps2pbes converts this formula to 

`nu Z. mu X0. Z`

this formula is logically equivalent to true (e.g., the process `init delta;` does satisfy this formula).

**Comment by wiegerw** [comment]
I think the problem is in line 108 of mcrl2/modal_formula/detail/state_formula_name_clash_resolver.h. There 'operator()' is used in the builder instead of 'apply'. Due to this the variable is not renamed.

**Comment by jgroote** [comment]
This problem appears to be resolved with the commit mentioned above.
