### ISSUE TITLE
Multiactions wrongly renamed to tau in ltsconvert

### ISSUE THREAD

**Issue by markuzzz** [mCRL2org/mCRL2#1648]
The tool ltsconvert renames ALL multiactions to tau when the flag --tau=... is used.

Minimal working example.
Model:
act
	a; b; c; d;
proc
	 P = a.b|c.d.delta;
init
 allow({a,b|c,d},P);

linearize with: mcrl22lps model.mcrl2 model.lps
generate state space with: lps2lts model.lps model.lts
Reduce with: ltsconvert model.lts model_reduced.lts --tau=a --equivalence=bisim
Expected behaviour: only a is renamed to tau
Actual behaviour: both a and b|c are renamed to tau

The bug seems to be independent of the equivalence used. The bug does not occur when the --tau flag is not used.
mCRL2 version: latest nightly build, 202106.0.7fc881c54f
OS: macOS Big Sur version 11.4

**Comment by jgroote** [comment]
I can confirm this problem.

**Comment by jgroote** [comment]
This problem is resolved in the commit mentioned above. Thanks for reporting it.
