### ISSUE TITLE
Option -c on lps2lts runs out of memory after a few states

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1649]
Option `-c[NAME]` for `lps2lts` can be used to "apply prioritization of transitions with the action label NAME" (taken from documentation). However, after trying this option out it does not seem that that is actually what it does. For instance using the following specification (called `test.mcrl2`)
```
act a;
init tau.delta + a.delta;
```
and using the commands
```
mcrl22lps -v test.mcrl2 test.lps
lps2lts -v -ctau test.lps test.lts
```
produces an LTS without any transitions, while from the documentation I would expect that the LTS would have one transition, namely the `tau`-transition due to `tau.delta`.
Since this option stems from tau-prioritisation in case of tau-confluence, I tried the same with the specification
```
act a;
init tau.a.delta + a.tau.delta;
```
which results in an LTS with only an `a`-transition. This leads me to believe that the option `-ctau` not only prioritises `tau`, but also checks for tau-confluence and removes the prioritised `tau`-transitions. I have also tried to use this option on a larger model, but it got stuck after finding 2 states, completely flooding my memory, while I can generate the LTS without `-ctau` just fine. This does still not explain the resulting LTS of the first example for me though.

I feel like option `-c` is too specialised and does too much work, most of which is not explained in the documentation.
 - I think checking confluence should not be part of option `-c`, we have the tool `lpsconfcheck` for that. Also, if you know that the action that you prioritise is confluent by design of the model, you don't want to waste time checking confluence. I would expect that using option `-c` makes state space generation faster, since it reduces the search space.
 - Removing the prioritised transitions seems undesired in general. In case the prioritised action is `tau`, it might make sense to remove it (in case it is confluent), but this can also be done easily with `ltsconvert -ebranching-bisim` afterwards. In case the prioritised action is not `tau`, it is effectively removing behaviour.

I think that we should replace option `-c` with an option that only does the prioritisation. This more general option is still very useful for the case of tau-confluence, but can also be useful for other cases. The name of the option could then be changed to something like `-p`, `--prioritise`.

I think the option would be even better if you could provide more than one action and give different actions different priorities (for instance prioritised in the order that they are provided), but that might be something for a second ticket.

**Comment by jgroote** [comment]
This option -c applies tau priorisation on action with the name ctau, and removes prioritised tau's. It does not check for confluence. This can be done by lpsconfcheck. By giving -c an optional argument it checks tau priorisation for the argument.

Removing the tau can  be very helpful for large statespaces. There have been cases where removing confluent
tau's reduced the statespace by a factor 30, meaning that it could not have been generated otherwise. We may
adapt the explanation of the option if it is confusing, but changing a flag should only be done with extremely strong reasons.

It is interesting to see the example where using the option -c requires far more time than without using this option. This may suggest a problem with the internal algorithms.

Maybe multiple actions that are reduced in order might be useful in -c. I am not yet convinced, and it would be good to see a use case. Besides that it might be reasonably easy to implement.

**Comment by tneele** [comment]
I agree with @jgroote on every point, and I'm pretty sure that confluence reduction works as intended, besides perhaps a bug here or there. The behaviour of `lps2lts -c` on the two examples you included is expected: the `tau` transition is prioritised and subsequently collapsed.

I would be interested to see the larger example that causes an OOM. I don't have an explanation for that behaviour right now.

**Comment by Valo13** [comment]
Yeah, after some discussion with Tim and some more thinking I feel like I was thinking too easily concerning tau-confluence, so lets just focus on the fact that `lps2lts -ctau` got stuck on an mCRL2 specification of mine.
The specification is [vehicle_lift_spec.txt](https://github.com/mCRL2org/mCRL2/files/6747779/vehicle_lift_spec.txt). It is generated from a collection of OIL component specifications based on the vehicle lift example from the mCRL2 tool-set (but simpler and with faulty behaviour). Lines 1-80 define a bus that is communicated over, lines 86-171 define a lift, lines 178-254 define a user (who first presses up on one lift and then down on another) and lines 262-277 synchronise all components. Every component communicates using an FIFO input queue like I explained in my colloquium talk recently (with some adjustments).
All actions that concern pulling something from a queue are hidden. Since the action of pulling something from a queue is independent of any other action in the system, I believe that all `tau`-actions are confluent. This is strengthened by the fact that reducing the corresponding LTS (computed without using `-ctau`) modulo divergence preserving branching bisimulation removes all `tau`-actions.

Using the commands
```
mcrl22lps -v vehicle_lift_spec.txt lift.lps
lps2lts -v -ctau lift.lps lift.lts
```
results in lps2lts being stuck after finding 2 states.

**Comment by Valo13** [comment]
I can confirm that it works properly now 👍
