### ISSUE TITLE
Opening mCRL2-IDE from mCRL2-GUI fails with the Windows 10 installed 202106 release

### ISSUE THREAD

**Issue by GijsGroote** [mCRL2org/mCRL2#1652]
When opening the IDE from the GUI, mCTRL2-GUI: File -> Open mctl2ide
the mCTL2-IDE cannot be found. This probably is a result of unsuccessfully adding the path to the environmental variables. Which has a clear  [error message](https://imgur.com/a/LTykiq3).

mCTL2 version: 202106.0
OS: Windows 10

Very similar issue here #1487

**Comment by Valo13** [comment]
Did you move the location of (one of) the executables? It first tries to search for `mcrl2ide` in the same folder that `mcrl2-gui` is in, so if you moved them this could fail. If that doesn't work it uses PATH, so adding the executables folder to PATH should be a fix as well.

**Comment by GijsGroote** [comment]
No folders/files were moved after installation in the default folder C:\Program Files\mCRL2\

Adding the path of the  program executables C:\Program Files\mCRL2\bin to the environmental variables does not resolve the issue. Also from the command line opening both mCRL-gui and mCRL2ide does work. Could I check where mCRL2-gui tries to find mCRL-ide after clicking "Open mcrl2ide" ?

**Comment by Valo13** [comment]
Hmm, that's odd. I can indeed reproduce this bug on my installation of mCRL2 on Windows 10, but I cannot reproduce this on my locally built release, which should be the same because I used that to make the installer...

If you meant where in the code it is called, that happens [here](https://github.com/mCRL2org/mCRL2/blob/54fa1483c92c95574457c430ae359cba4c1eca89/tools/release/mcrl2-gui/mainwindow.cpp#L56).

**Comment by Valo13** [comment]
I managed to get it working on my end, see commit 397c0f92c2a918339961cacb480571c6beb10de3. I'll update you when the fixed version is published on the site so you can check whether it works on your end too.

**Comment by Valo13** [comment]
I think it is related to [this Qt bug](https://bugreports.qt.io/browse/QTBUG-57687)

**Comment by Valo13** [comment]
The Windows release files have been updated with this fix.
@GijsGroote Could you download the current release again and check whether it works as intended now?

**Comment by GijsGroote** [comment]
With the current release (202106.0) it does open the IDE from the GUI. Thank you
