### ISSUE TITLE
Lpsxsim crash

### ISSUE THREAD

**Issue by markuzzz** [mCRL2org/mCRL2#1658]
Lpsxsim crashes when selecting a specific transition.
Tool version: latest nightly build for Mac OS (202106.0.d775157140)

Can be reproduced by taking two transitions in the LPS using lpsxsim.
selectMultiStep(none, StateConfig(F_P3_SR_STD_1, [StateConfig(OPERATING, [StateConfig(Initial1, []), StateConfig(Initial2, [])])]))
selectMultiStep(none, StateConfig(F_P3_SR_STD_1, [StateConfig(OPERATING, [StateConfig(STOPPED, [])])]))

The issue is only present when using the jitty rewriter, jittyc works fine.

Attachments: crash report MacOS, mCRL2 and LPS files
[Archive.zip](https://github.com/mCRL2org/mCRL2/files/7090923/Archive.zip)
[crash_report.txt](https://github.com/mCRL2org/mCRL2/files/7090924/crash_report.txt)

**Comment by Valo13** [comment]
I cannot reproduce this on Windows 10 (it does not crash and behaves as expected).

**Comment by mlaveaux** [comment]
The crash report suggests that rewriting ran out of stack space. From my understanding there is an issue with Qt/GUI tools that causes the stack size to be much more limiting then the command line tools especially on Mac.

**Comment by mlaveaux** [comment]
We cannot resolve this issue since it is a Qt limitation. The rewriter could be rewritten to use an explicit stack data structure to rely less on the OS stack, which has been partially done.
