### ISSUE TITLE
LPS of two processes written in a different way

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1667]
I believe that the following two definitions are exactly same but written in a different way
Def-1: `P(n:Nat) = a.(n mod 2 == 0) -> P(0) <> P(1);`
Def-2: `P(n:Nat) = a.P(if (n mod 2 == 0, 0, 1));`

But specification wise their LPSs are different in term of complexity. 
Def-1 has LPS as:
```
 proc P(n_P: Nat) =
       sum e_P: Bool.
         (if(e_P, !(n_P mod 2 == 0), n_P mod 2 == 0)) ->
         a .
         P(n_P = if(e_P, 1, 0))
     + delta;
```

While Def-2 has LPS as:
```
P(n_P: Nat) =
       a .
         P(n_P = if(n_P mod 2 == 0, 0, 1))
     + delta;
```
Is it a good idea that the algorithm(s) behind generating an LPS can realize this similarity?

**Comment by mlaveaux** [comment]
After some internal discussion we have come to the conclusion that unfortunately it is generally not feasible to make such a guarantee of syntactically equal LPSs. You can eliminate the sum from the LPS resulting from Def-1 by using `lpssuminst -b`. This would result in a simpler (but still different) LPS.
