### ISSUE TITLE
Formatting of generated tool options on website inconsistent with command line tool options

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1677]
When showing the options of a tool using --help on the command line, an option of the form `--long=VALUE` is shown on the website under tool documentation as `--longVALUE`.
For instance, for `pbessolve` the `--file` option is shown on command line as `--file=NAME` but on [the website](https://mcrl2.org/web/user_manual/tools/release/pbessolve.html#command-line-options) it says `--fileNAME`.

**Comment by jgroote** [comment]
On line 138 of the file doc/sphinx/_extensions/manual.xsl 
  <xsl:if test="$long='yes'">

Maybe the $ should be removed to solve this issue. As "make doc" does not work (anymore), I cannot check this and I find it too risky to just check this in and see what will have happened tomorrow. 

Therefore I leave this to Jeroen to solve.
