### ISSUE TITLE
mcrl2xi does not have fixed width fonts on the mac. 

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1680]
mcrl2xi does not have fixed width fonts (anymore?) on the mac. This makes indentation 
of mcrl2 rather cumbersome.

**Comment by Valo13** [comment]
mcrl2xi uses the same text editor as mcrl2ide, Does the issue occur in mcrl2ide as well?

**Comment by jgroote** [comment]
No. In mcrl2ide a fixed width font appears. But I can remember that something was changed in mcrl2ide, as it used to have a non fixed width font. Maybe the same solution can be applied to mcrl2xi.

**Comment by Valo13** [comment]
I'm pretty sure that change was made in shared code. Is the version of mcrl2xi the same as mcrl2ide?

**Comment by Valo13** [comment]
Fixed with commit 5592a31d4fb6e5f76a867bbce6b46d21eb83b44d
