### ISSUE TITLE
Linearisation leads to undefined data variables. 

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1685]
Consider the following linear process. 
```
act a1;
proc P(x:Nat) = a1.P();
init P();
```
If this process is linearised, the result is the following.
```
act  a1;

proc P(x_P1: Nat) =
       a1 .
         P()
     + delta;

init P(x);
```
Now the variable x in the init clause is undefined. This is clearly undesired.

**Comment by jgroote** [comment]
The previous commit should have resolved this bug.

**Comment by mlaveaux** [comment]
This seems to be resolved, but the issue was not yet closed.
