### ISSUE TITLE
Graphical tools produce no text output on Windows

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1686]
Executing `ltsgraph --help` produces no output in Windows Terminal, Command Prompt and Powershell on Windows 10 (and 11) version 10.019044. This is with the latest release, but the same applies to the previous release. Command line tools such as `lps2lts` do produce output just fine:

```
PS C:\Users\mlaveaux> lps2lts --version
lps2lts mCRL2 toolset 202206.0 (Release)
Copyright (c) 2022 Technische Universiteit Eindhoven.
This is free software.  You may redistribute copies of it under the
terms of the Boost Software License <http://www.boost.org/LICENSE_1_0.txt>.
There is NO WARRANTY, to the extent permitted by law.

Written by Wieger Wesselink.
```

Passing a filename to `ltsgraph` does work, so the arguments seem to be parsed. Control to the terminal is also immediately returned after starting `ltsgraph`, which might be related.

**Comment by Valo13** [comment]
I can reproduce this for command prompt and powershell on WIndows 10. The correct output does appear when using git bash.
