### ISSUE TITLE
ltsview generates OpenGL error: 1282 on Ubuntu

### ISSUE THREAD

**Issue by matifch** [mCRL2org/mCRL2#1688]
While exporting an output of the tool "ltsview" as a bitmap over Ubuntu, I'm facing OpenGL error: 1282.
Versions are:
mcrl22lps mCRL2 toolset 202206.0 (Release)
Ubuntu 20.04.4 LTS

Another issue while doing the same is that if I change height and width before saving, the image is vanished from the tool and generates the same error.

**Comment by jgroote** [comment]
When doing this on the mac, I get the same error, but the .bmp picture that is generated is actually fine.
Changing the height and width does not influence the picture though...

We are planning to refresh ltsvies and diagraphica soon, and this problem should be addressed there.

**Comment by mlaveaux** [comment]
Refactoring ltsview will take more time, but since the output is generated correctly despite the error the issue can be closed. Should be checked again when ltsview has been replaced.
