### ISSUE TITLE
F3 / apple-G to search again in mcrl2-ide

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#1693]
In mcrl2ide there is a Find and Replace option.
When in the main window of mcrl2ide, a particular string must be searched again,
this must be done by going to the Find and Replace window and click "Find", or
press return.

The standard way on a mac for this is to press apple-G in the mcr2ide window and
the next element will be found. On windows -according to Ferry- this is F3. 

Is it possible to add apple-G on a mac and F3 on windows machines, and possibly
also the natural choice on a linux platform.

**Comment by Valo13** [comment]
I've never heard of F3 being used for this. After some searching, it seems that some pages do mention this, but for the tools that I tried to use it (Eclipse, Notepad++, Word), only Notepad++ reacted accordingly to F3. Actually, in Word F3 is already mapped to something else.
There is Qt support for it though, so I'll add it (together with find previous as Shift+command+G or Shift+F3)
