### ISSUE TITLE
The selection is Diagraphica's edit mode is broken

### ISSUE THREAD

**Issue by FerryT** [mCRL2org/mCRL2#1720]
While testing the Qt6 build (feature/qt6) under windows (MSVC) I came across a few issues.
1. ~In ltsview, changing the "accuracy" of the diagram causes it to crash.~
2. In Diagraphica, in edit mode, selections do not work anymore.
I will update this list when I find more.

**Comment by mlaveaux** [comment]
Changing the "accuracy" in ltsview yields some kind of OpenGL crash, which is hard to debug since this tool is still using the compatibility mode. Not sure why switching to Qt6 has an influence on this yet, maybe something changed about the way that OpenGL is initialised in Qt.

**Comment by mlaveaux** [comment]
I have removed the accuracy option since I cannot fix this anyway. It might be worth to refactor the ltsview drawing at some point anyway.

**Comment by mlaveaux** [comment]
The only remaining issue found so far is the one pertaining Diagraphica, so repurposed this issue to keep track of that issue.

**Comment by mlaveaux** [comment]
This issue has been fixed by @FerryT as well as other subtle bugs.
