### ISSUE TITLE
Enumerator bug in lps2lts when using multiple threads and tau-prioritisation

### ISSUE THREAD

**Issue by Valo13** [mCRL2org/mCRL2#1729]
Given the mCRL2 specification [pingpongcnew2ctau_spec.txt](https://github.com/mCRL2org/mCRL2/files/13378137/pingpongcnew2ctau_spec.txt), if I run the commands
```
mcrl22lps pingpongcnew2ctau_spec.txt ppn.lps
lps2lts -rjittyc -ctau --threads=16 ppn.lps ppn.lts
```
there is about 50% chance that lps2lts will execute correctly. For the other 50%, it terminates after about half a minute with the error
```
terminate called after throwing an instance of 'mcrl2::data::enumerator_error'
  what():  Condition v_OIL_cid_pingpongcnew_P5 in v_OIL_clist_pingpongcnew_P16 && v_OIL_ctype_pingpongcnew_P16(v_OIL_cid_pingpongcnew_P5) == OIL_spec_type_pingc && v_OIL_success_pingpongcnew_P16(v_OIL_cid_pingpongcnew_P5) && v_OIL_unconsumed_pingpongcnew_P16(v_OIL_cid_pingpongcnew_P5) == pingpongcnew_OIL_event_type_no_event && !(v_OIL_queue_pingpongcnew_P16(v_OIL_cid_pingpongcnew_P5) == []) && head(v_OIL_queue_pingpongcnew_P16(v_OIL_cid_pingpongcnew_P5)) == pingpongci_ping_set_pong_call(v_OIL_cid_pingpongcnew_P5, the_pong_pingpongcnew_P16) && !(pingc_GET_root_region(v_OIL_state_pingpongcnew_P16(v_OIL_cid_pingpongcnew_P5)) == pingc_oil_auto_type_root_region_type_busy0 && 0 < pingc_GET_i(v_OIL_state_pingpongcnew_P16(v_OIL_cid_pingpongcnew_P5))) does not rewrite to true or false. Culprit: (pingpongcnew_GET_root_region(pingc_OIL_IS_struct(pingc_oil_auto_type_root_region_type_idle1, 3, 3)) == pingpongcnew_oil_auto_type_root_region_type_root_region_auto_35 && 2 == pingpongcnew_GET_ping1(pingc_OIL_IS_struct(pingc_oil_auto_type_root_region_type_idle1, 3, 3)) && 0 == pingpongcnew_GET_pong1...
<SOME_PATH>: line 23: 1008920 Aborted                 (core dumped) lps2lts -rjittyc -ctau --threads=16 ppn.lps ppn.lts
```
This is run on an HPC cluster using the 202307.0 release.

Some notes:
 - The mCRL2 specification is one that is automatically generated from a set of OIL specifications. This specification defines a system of 5 component instances that communicate with each other.
 - The mCRL2 specification uses a single process to define this behaviour, with functions as process parameters that map each component instance to some data, such as its state. In a similar mCRL2 specification, where every component is defined using a separate process without function process parameters, which are then put in parallel, this issue does not occur.
 - The error also happens without option `-rjittyc`. If I remove options `--threads=16` and `-ctau` the error does not occur (within 5 runs).
 - The error seems to always happen at the beginning of state space generation. Even for models with an increased number of component instances for which the state space generator takes more than an hour, the error occurs within half a minute, or the state space generator succeeds.

**Comment by tneele** [comment]
I did not look at your specification in detail, but this kind of non-deterministic behaviour can be caused by a non-confluent rewrite system. Is it possible that your rewrite rules are non-confluent?

**Comment by Valo13** [comment]
I'm quite certain the rewrite system is confluent. For each self-defined map F (that is used) I only define one equation with F on the left-hand side. Each of these equations is of the form `F(x, y, ...) = ...` where `x` and `y` are variables, constants or constructors of the form `S(u, v, ...)` where `u` and `v` are variables or constants. No equations exist of the form `S(u, v, ...) = ...` for any constructor S.

Also, I'd expect that if the rewrite system would not be confluent, then it should also go wrong without the options `--threads=16` and/or `-ctau`.

**Comment by mlaveaux** [comment]
After finally fixing some other data races and looking at this issue it is now clear that tau prioritization was never made thread safe since it reads/writes/data races on a single m_recursive boolean. This should be repaired or disallow the usage of tau prioritization in combination with multiple threads.
