### ISSUE TITLE
Erroneous Explaination in Documentation

### ISSUE THREAD

**Issue by l-fran** [mCRL2org/mCRL2#1732]
In the Documentation for `Data Specification` under the Section `Specifying Sorts` (https://github.com/mCRL2org/mCRL2/blob/master/doc/sphinx/user_manual/language_reference/data.rst#specifying-sorts) you write:

> If we now interpret the term `cdub(true, num)` (where *num* is a term
of sort ``Positive``) as "twice the number that *num* represents", and interpret
`cdub(false, num)` as "twice the number that *num* represents, plus 
one", then we have created a binary encoding of the positive numbers. For 
instance, ``cdub(false, one)`` represents the number 2, and 
``cdub(false, cdub(true, cdub(false, one)))`` represents the number 10.

Reading this, should't be `cdub(false, one)` be 3 and not 2?

**Comment by jgroote** [comment]
You are completely right.

But the standard data types add +1 for cdub(true, n), contrary to what the text states.
I adapted the text such that the use of true and false are reversed. In that case the
examples are actually correct.

Thanks for noting this. The change should appear at the next succesful build of the toolset.

Regards, Jan Friso
------------------------------------------------------------------------------------------------------------------------
Jan Friso Groote, Eindhoven University of Technology, Department of Mathematics and
Computer Science, Metaforum room MF 6.079b, Groene Loper 5, 5612 AE Eindhoven.
The Netherlands. +31-40-247 5003, secretary: +31-40-247 5145,
***@***.******@***.***>, www.win.tue.nl/~jfg<http://www.win.tue.nl/~jfg>, Skype: janfriso
Home: Hoekstraat 56, 5674 NP Nederwetten, +31 40 2845414, +31 6 81922128


From: l-fran ***@***.***>
Date: Tuesday, 12 December 2023 at 10:18
To: mCRL2org/mCRL2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mCRL2org/mCRL2] Erroneous Explaination in Documentation (Issue #1732)

In the Documentation for Data Specification under the Section Specifying Sorts (https://github.com/mCRL2org/mCRL2/blob/master/doc/sphinx/user_manual/language_reference/data.rst#specifying-sorts) you write:

If we now interpret the term cdub(true, num) (where num is a term
of sort Positive) as "twice the number that num represents", and interpret
cdub(false, num) as "twice the number that num represents, plus
one", then we have created a binary encoding of the positive numbers. For
instance, cdub(false, one) represents the number 2, and
cdub(false, cdub(true, cdub(false, one))) represents the number 10.

Reading this, should't be cdub(false, one) be 3 and not 2?

**Comment by mlaveaux** [comment]
This appears to have been resolved.
