### ISSUE TITLE
lps2lts no longer outputs to stdout by default

### ISSUE THREAD

**Issue by Kevinjil** [mCRL2org/mCRL2#1759]
According to the documentation, lps2lts outputs to stdout if no output file is specified.

## Expected behavior
```bash
$ echo "act a; proc P = a . P; init P;" | mcrl22lps | lps2lts
```
Should warn `No output format set or detected; using default (lts).` on stderr and print the LTS in the internal binary format to the console such that it can be piped to the next command.

The behavior should be equivalent to
```bash
$ echo "act a; proc P = a . P; init P;" | mcrl22lps | lps2lts /dev/stdin /dev/stdout 
No output format set or detected; using default (lts).
����▒X�[��[��]▒[��\�[@'�0
                         [\W�▒\��)���,n�,�L@H�����}������Սѽ��
�:90�9��4��[�X[��ܝYX`z�s#+3Ks+"��+
                                  ` J#
                                      �
�
 �K V�,n�-��M���▒����Ț������d6�2��:<�;,�▒������ؾ�����v�
```

## Actual behavior
```bash
$ echo "act a; proc P = a . P; init P;" | mcrl22lps | lps2lts
$ echo $?
0
```
Exits without output with exit code 0.

## Environment
Linux 6.6.22-1-lts
zsh shell
Both mCRL2 version 202307.1 and the master branch tested.

**Comment by tneele** [comment]
The expected behaviour you describe is indeed how most tools behave. I think that an exception was made for lps2lts because in some cases it is desirable to only use one of the other features of lps2lts (counting states, finding deadlocks etc.) and not output anything (because this can be expensive, in time or disk space). Of course this design decision can be changed, I think @jgroote's opinion is relevant.

**Comment by Kevinjil** [comment]
Thank you for the input @tneele.

After discussion with @jgroote, we concluded that by default there should be no LTS output to `stdout`. Only if the output format is specified, the default output should be `stdout`.

A documentation update and a fix is needed for some output formats:
```shell
$ echo "act a; proc P = a . P; init P;" | mcrl22lps | lps2lts -olts                                   
[error]   Fail to open file  for writing.
$ echo "act a; proc P = a . P; init P;" | mcrl22lps | lps2lts -oaut
[error]   cannot open '' for writing
$ echo "act a; proc P = a . P; init P;" | mcrl22lps | lps2lts -ofsm
---
---
1 1 "a"
$ echo "act a; proc P = a . P; init P;" | mcrl22lps | lps2lts -odot
cannot open DOT file '' for writing.
```
