### ISSUE TITLE
Qt 6.7 added a Windows 11 theme, which enabled dark mode, and this makes the icons hard to see in mcrl2ide

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1762]
This is mCRL2ide compiled with Qt 6.7. Although the icons are also the same for macOS dark mode it seems to me like the background is darker, thus making it hard to see them.

![image](https://github.com/mCRL2org/mCRL2/assets/2884328/1fe38823-7d6c-422c-89e7-049ee77dc415)

Whereas the nightly version, using Qt 6.6, looks fine:

![image](https://github.com/mCRL2org/mCRL2/assets/2884328/e77267d1-30ce-43e9-bb71-96cfb7ba89ad)

**Comment by krab** [comment]
Yep they added dark mode but still there is no simple way to detect these changes.
https://github.com/search?q=repo%3Aqt%2Fqtbase%20colorSchemeChanged&type=code
Their signal `colorSchemeChanged` never emits by Qt developers, none QPA plugins emits it if I understand correctly.

**Comment by mlaveaux** [comment]
Currently, we do not have suitable icons for the Windows dark mode palette. So my proposed solution would be to set `windows:darkmode=0` on startup to disable dark mode on Windows completely for the time being.

**Comment by Valo13** [comment]
I could make some icons suitable for light mode. Concerning detection of dark mode, I can remember adding basic code for that, for instance for the text editor syntax colouring, that simply checks whether the background is dark and if so, uses dark mode defaults. I guess the same thing can be done here.

**Comment by mlaveaux** [comment]
If you want to make icons for light than that could work as well for mcrl2ide. Perhaps for ltsgraph it might still be useful to disable dark mode due to the white canvas. Also my proposed solution does not work for the menus for whatever reason.

![image](https://github.com/mCRL2org/mCRL2/assets/2884328/799f5c43-9b0c-4dc2-87de-191bbf18671a)

**Comment by mlaveaux** [comment]
I figured out how to disable the dark mode completely for the moment, when the dark icons are ready (and perhaps some other styling) it can be enabled properly.

**Comment by mlaveaux** [comment]
The issue has been fixed, icons can be added in a separate issue/pull request.
