### ISSUE TITLE
The dnj branching bisimulation algorithm triggers an assertion with the --tau option

### ISSUE THREAD

**Issue by mlaveaux** [mCRL2org/mCRL2#1777]
For the following LTSs the original dnj branching bisimulation algorithm triggers an assertion when using the --tau option. Running in release mode it seems like the actual answer is consistent with the other branching bisimulation algorithms.

[l4.aut.txt](https://github.com/user-attachments/files/15760032/l4.aut.txt)
[l3.aut.txt](https://github.com/user-attachments/files/15760033/l3.aut.txt)

```
ltscompare l3.aut.txt l4.aut.txt -ebranching-bisim --tau=b
No input format is specified. Assuming .aut format.
ltscompare: /home/mlaveaux/mCRL2/libraries/lts/include/mcrl2/lts/detail/liblts_bisim_dnj.h:2893: bool mcrl2::lts::detail::bisim_dnj::part_trans_t::make_noninert(mcrl2::lts::detail::bisim_dnj::pred_entry *const, mcrl2::lts::detail::bisim_dnj::block_bunch_slice_iter_or_null_t *const): Assertion `new_action_block_pos == new_noninert_bunch->end || (nullptr == new_action_block_pos[-1].succ && new_action_block_pos - 1 == new_noninert_bunch->end)' failed.
Aborted
```

**Comment by dnjansen** [comment]
The assertion did not take into account a situation if the last label has zero transitions. I have reformulated the assertion to include that case.
Is there a way to create labels with zero transitions in other places than the last label, so that one might test that as well?

**Comment by dnjansen** [comment]
I think it’s solved, I am not sure whether I can close the issue or I should let one of you run additional tests before closing.

**Comment by mlaveaux** [comment]
I have re-enabled the test that was used to find this case as it seem to work now. I am not sure why reading an .aut file results in an LTS where one label has zero transitions, but I guess in general this would only be created in code.

**Comment by jgroote** [comment]
Regarding the question of David, I believe that by using the --tau option, you can hide multiple action labels at once. These labels will not occur anymore in the transition system, and one of them will not be positioned as the last label. It is also possible that both labels are not the last label.
