### ISSUE TITLE
Error in mCRL2-ide with tutorial book example: `pbessolve: option -r, --rewriter specified more than once`

### ISSUE THREAD

**Issue by MSoegtropIMC** [mCRL2org/mCRL2#1784]
I am following this [tutorial text book](https://link.springer.com/book/10.1007/978-3-031-23008-0), and try to reproduce my manual solutions for exercise 6.3. in mCRL2-ide.

I am using as specification:
```
act a, b;

proc P = a;

init P;
```
and as properties:
```
<a>[a]<a>true
[a]<a>[a]false
```
When I select "Verify all properties" I get the output:
```
##### PARSING SPECIFICATION #####
##### CREATING LPS #####
Up to date LPS already exists
##### PARSING PROPERTY EX63_1 #####
##### CREATING PBES #####
Up to date PBES already exists
##### SOLVING PBES #####
pbessolve: option -r, --rewriter specified more than once
Try 'pbessolve --help' for more information.
```
Running the same files in mCRL2-gui or using command line tools works fine.

I am on MacOS and using mCRL2 2024.07.0.

**Comment by mlaveaux** [comment]
Apparently something broke on other platforms. It should be fixed in the coming nightly and after that we will probably prepare a minor release.

**Comment by MSoegtropIMC** [comment]
Perfect, thanks! I will test it with the nightly build latest on Monday and report here if it works.

**Comment by mlaveaux** [comment]
We released a minor version that should hopefully resolve this issue.

**Comment by MSoegtropIMC** [comment]
@mlaveaux : thank you! I just tested 2024.07.1 (on MacOS) and can confirm that it does work now.

**Comment by MSoegtropIMC** [comment]
P.S.: I leave it to you to close the issue.
