### ISSUE TITLE
data-only specifications no longer accepted as correct mcrl2 specification by mcrl2-gui/mcrl2xi 202407.1 (Release)

### ISSUE THREAD

**Issue by gjveltink** [mCRL2org/mCRL2#1785]
In my courses I always start with simple algebraic data specifications before I turn to process specifications.
Starting with the latest release (202407.1) these specifications can no longer be parsed by mcrl2xi.

Example:
[01_Peano_redux.mcrl2.txt](https://github.com/user-attachments/files/17084083/01_Peano_redux.mcrl2.txt)

The parser reports:
**[14:41:52 info] Parsing and type checking specification
[14:41:52 error] Line 43, column 48: syntax error after ';'
  	t1 = plus(s(s(zero)), s(s(s(zero)))); 		% 2 + 3
                                                  ^
[14:41:52 error] Specification does not contain a valid data or mCRL2 specification.
syntax error**

Even the error message is misleading.

I would expect to still be able to parse data-only specifications.
Please consider re-instating this possibility.

I will now try to find a low-intrusive workaround before next week's course. :-(

**Comment by gjveltink** [comment]
OK here is a workaround that can be added to data-only specifications.

[00_Minimal.mcrl2.txt](https://github.com/user-attachments/files/17084119/00_Minimal.mcrl2.txt)

**Comment by mlaveaux** [comment]
Looking at the code there was a check that should have never worked, but maybe it broke with the switch from Qt5 to Qt6. I have fixed it in the master branch, perhaps we make release this week to also solve another issue. The easiest workaround is to put `init delta;` after the data specification.
