### ISSUE TITLE
Improve navigation features

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#614]
*Issue migrated from trac ticket # 611*

**component:** ltsview | **priority:** minor | **keywords:** navigation viewpoint pan zoom rotate

#### 2009-06-08 15:05:06: s.c.w.ploeger@tue.nl created the issue

___
Currently, LTSView supports navigation by panning, zooming and rotating. Rotation should be extended further, allowing rotation around different points.

Moreover, each of the navigation versions should allow for more accurate navigation: currently, the camera often moves too fast on a minor mouse move.

Finally, it would be very helpful if viewpoints could be stored (e.g. in a file) and reloaded later.

(These features were requested by Bas van Vlijmen.)

**Comment by tneele** [comment]
In my view, the most important issue here is to support rotation around different points. However, this is not easy to implement, especially the GUI aspect of selecting a rotation point in 3D space. We will leave ltsview as it is.
