### ISSUE TITLE
Additions to type checking of data expressions

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#645]
*Issue migrated from trac ticket # 642*

**component:** Data Library | **priority:** minor

#### 2009-09-21 11:10:41: @wiegerw created the issue

___
It would be useful to have functions that check data expressions for the following:

1) in every function application f(x) with f:A->B check that x has type A

2) in every equation t1=t2 check if the types of t1 and t2 are equal

Such functions can be added to the well typedness checks, if this turns out to be not too expensive.

**Comment by tneele** [comment]
The responsibility of type checking data expressions should lie with the type checker, not in separate functions.
