### ISSUE TITLE
Document policies for testing and specification

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#908]
*Issue migrated from trac ticket # 905*

**component:** Documentation | **priority:** minor

#### 2011-12-15 14:57:02: @jkeiren created the issue

___
This item is meant to improve the quality of the code. Many tools lack proper specifications and have insufficient tests, or tests that do not measure the quality of the code. By making an overview of the current situation the awareness of the quality of the toolset will be improved.

An overview of tool statuses is available on http://mcrl2.org/mcrl2/wiki/index.php/Private:Tool_Status_Overview

**Comment by tneele** [comment]
This a duplicate of #1088.
