### ISSUE TITLE
Implement Map/Filter/Reduce on containers

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#914]
*Issue migrated from trac ticket # 911*

**component:** Data Library | **priority:** minor

#### 2011-12-15 15:10:24: @jkeiren created the issue

___
With the introduction of the new representation for set and bag we are now able to (amongst other things) use finite sets and bags as state parameters in an effective manner. The common operators (element test, union, difference etc.) have all been adapted to make sure that they work nicely on these finite collections. For set/bag comprehensions there has been no such adaptation. Of course, in general such a adaptation will not be easy (if even practically possible). However, there are some typical uses of comprehensions that should be easy to capture (e.g. {x: D | x in S && f(x)}).

Another and perhaps more important omission is the fact that it is practically impossible to access (or "iterate") over the elements of a set or bag. A good example where this would be very helpful (if not necessary) is calculating the sum of the elements of a set of numbers or the number of elements in a finite set or bag.

We wish to introduce several generic functions to get a more complete set of functionality (practically). There are a few general guidelines that should be followed as much as possible.

    The language extension should be minimal; only those things that are essential should be added.
    The extension must be defined in terms of the languages as presented to the user. I.e. implementation details should not be used. (Of course, there will also need to be a practical implementation.)

A more detailed description is available on
http://mcrl2.org/mcrl2/wiki/index.php/Private:Planning_Map_Filter_Reduce

**Comment by tneele** [comment]
This will not be added to the standard rewrite rules, since it requires a lot of work and carries the risk of introducing new bugs. Furthermore, according to @jgroote, this functionality is not used very often.
