### ISSUE TITLE
Integrate the simulation framework in ltsview

### ISSUE THREAD

**Issue by jgroote** [mCRL2org/mCRL2#987]
*Issue migrated from trac ticket # 985*

**component:** ltsview | **priority:** major | **keywords:** ltsview simulator

#### 2012-02-14 11:20:23: @jgroote created the issue

___
Ltsview currently has a simulation framework of its own.
This causes difficulties when loading traces without state information. Routines are available in the simulation framework
to resolve this. 

To limit software redundancy and to increase functionality
the simulationframework of ltsview needs to replaced bij the
simulator.

**Comment by tneele** [comment]
We decided not to address this issue, since the simulation framework is mostly LPS-based and ltsview is based on LTSs.
